### ISSUE TITLE
import_daily continuing to import_swissmedic, system exit happens to often

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#100]
It is now the third month in a row we got this error. This Error got worse when switching from `Ruby 2.5.0` to `Ruby 2.7.1`.

```
Plugin: ODDB::SwissmedicPlugin

Error: SystemExit
Message: SystemExit
Backtrace:
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/inflater.rb:44:in `inflate'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/inflater.rb:44:in `internal_produce_input'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/inflater.rb:15:in `sysread'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/input_stream.rb:82:in `sysread'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/ioextras/abstract_input_stream.rb:33:in `read'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/document.rb:59:in `read_io'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.10.4/lib/nokogiri/xml/document.rb:59:in `parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.10.4/lib/nokogiri/xml.rb:65:in `parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/ooxml_object.rb:110:in `parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/worksheet.rb:735:in `parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/ooxml_object.rb:440:in `block in parse_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/entry.rb:522:in `get_input_stream'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/ooxml_object.rb:440:in `parse_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:91:in `block in load_related_files'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:76:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:76:in `load_related_files'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:179:in `load_relationships'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:92:in `block in load_related_files'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:76:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:76:in `load_related_files'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/relationships.rb:179:in `load_relationships'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/objects/root.rb:66:in `parse_zip_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/parser.rb:8:in `block in parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.3.0/lib/zip/file.rb:114:in `open'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.30/lib/rubyXL/parser.rb:7:in `parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.7/lib/compatibility.rb:10:in `open'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/swissmedic-diff-0.2.7/lib/swissmedic-diff.rb:184:in `diff'
/var/www/oddb.org/src/plugin/swissmedic.rb:340:in `update'
/var/www/oddb.org/src/util/updater.rb:406:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:511:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:404:in `update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:212:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
running only `jobs/import_swissmedic` in a separate screen works just fine.

**Comment by zdavatz** [comment]
happened again on 5.5.2020

**Comment by ngiger** [comment]
https://github.com/zdavatz/oddb.org/blob/master/src/util/updater.rb Zeile 205 
findet man die Sequenz der ARbeiten vom import_daily

**Comment by zdavatz** [comment]
Das ist der neue Crontab Eintrag:
![latest-screenshot](https://user-images.githubusercontent.com/4953/85371988-72aa2680-b531-11ea-90a9-8f1c7779b20f.png)

**Comment by ngiger** [comment]
We remove Lines 212 till 214 as seen in 
https://github.com/zdavatz/oddb.org/blob/833bcda072c61b7bb16ac7408033d2e58f5311b9/src/util/updater.rb#L212
and add a new crontab entry at 09 to call jobs/import_swissmedic, which does exactly these things.

**Comment by ngiger** [comment]
See [(#100) Import Swissmedic removed from import_daily ](https://github.com/ngiger/oddb.org/commit/1ac2ce5df3aa2ca0abe5bf754db1b3d58d294f61)

**Comment by zdavatz** [comment]
* Analyse Absturz von import_daily bei import_Swissmedic (Memory_Profiler) 3 h.
