### ISSUE TITLE
ch.ODDB.org Report - Error: drugshortage.ch - 05/2020 - certificate expired error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#103]
```
Plugin: ODDB::ShortagePlugin

Error: OpenSSL::SSL::SSLError
Message: SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired)
Backtrace:
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:981:in `connect'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/net/http.rb:909:in `start'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:337:in `open_http'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:735:in `open'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:35:in `open'
/var/www/oddb.org/src/util/latest.rb:21:in `fetch_with_http'
/var/www/oddb.org/src/util/latest.rb:40:in `get_latest_file'
/var/www/oddb.org/src/plugin/shortage.rb:167:in `update_drugshortage'
/var/www/oddb.org/src/plugin/shortage.rb:52:in `update'
/var/www/oddb.org/src/util/updater.rb:354:in `block in update_drugshortage'
/var/www/oddb.org/src/util/updater.rb:511:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:352:in `update_drugshortage'
jobs/update_drugshortage:21:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/update_drugshortage:12:in `<module:Util>'
jobs/update_drugshortage:11:in `<module:ODDB>'
jobs/update_drugshortage:10:in `<main>'
```

**Comment by zdavatz** [comment]
It looks valid:
`openssl s_client -connect drugshortage.ch:443`

**Comment by zdavatz** [comment]
![latest-screenshot](https://user-images.githubusercontent.com/4953/83487454-59bad200-a4ab-11ea-9452-a520772010a8.png)

https://whatsmychaincert.com/?drugshortage.ch

**Comment by zdavatz** [comment]
https://www.agwa.name/blog/post/fixing_the_addtrust_root_expiration

**Comment by ngiger** [comment]
Auf thinpower sieht man auch den Fehler wie folgt
<pre>
ywesee@thinpower ~ $ curl https://www.drugshortage.ch/UebersichtaktuelleLieferengpaesse2.aspx
curl: (60) SSL certificate problem: certificate has expired
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
of Certificate Authority (CA) public keys (CA certs). If the default
bundle file isn't adequate, you can specify an alternate file
using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
the bundle, the certificate verification probably failed due to a
problem with the certificate (it might be expired, or the name might
not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
the -k (or --insecure) option.
</pre>

**Comment by zdavatz** [comment]
Problem behoben mit:

```
Edit /etc/ca-certificates.conf and put a bang/exclamation mark (!) before mozilla/AddTrust_External_Root.crt
Run update-ca-certificates
```

**Comment by zdavatz** [comment]
/usr/share/ca-certificates/mozilla/AddTrust_External_Root.crt

**Comment by zdavatz** [comment]
good check script: https://raw.githubusercontent.com/rubygems/ruby-ssl-check/master/check.rb

**Comment by zdavatz** [comment]
```
ywesee@thinpower /tmp $ /usr/local/bin/ruby-250 check.rb drugshortage.ch
Here's your Ruby and OpenSSL environment:

Ruby:           2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
RubyGems:       2.7.3
Bundler:        2.0.2
Compiled with:  OpenSSL 1.0.2g  1 Mar 2016
Loaded version: OpenSSL 1.0.2g  1 Mar 2016
SSL_CERT_FILE:  /etc/ssl/cert.pem
SSL_CERT_DIR:   /etc/ssl/certs

With that out of the way, let's see if you can connect to drugshortage.ch...

Bundler connection to drugshortage.ch:       failed  ❌  (certificate verification)
ERROR:  SSL verification error at depth 3: certificate has expired (10)
ERROR:  Certificate /C=SE/O=AddTrust AB/OU=AddTrust External TTP Network/CN=AddTrust External CA Root expired at 2020-05-30T10:48:38Z
RubyGems connection to drugshortage.ch:      failed  ❌  (certificate verification)
Ruby net/http connection to drugshortage.ch: failed  ❌

Unfortunately, this Ruby can't connect to drugshortage.ch. 😡
Your Ruby can't connect to drugshortage.ch because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine drugshortage.ch servers.
```

**Comment by zdavatz** [comment]
Damit klappt es schon mal:
```
/usr/local/bin/ruby-271 check.rb drugshortage.ch
Here's your Ruby and OpenSSL environment:

Ruby:           2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux]
RubyGems:       3.1.2
Bundler:        2.1.4
Compiled with:  OpenSSL 1.1.1b  26 Feb 2019
Loaded version: OpenSSL 1.1.1b  26 Feb 2019
SSL_CERT_FILE:  /etc/ssl/cert.pem
SSL_CERT_DIR:   /etc/ssl/certs

With that out of the way, let's see if you can connect to drugshortage.ch...

Bundler connection to drugshortage.ch:       success ✅
RubyGems connection to drugshortage.ch:      success ✅
Ruby net/http connection to drugshortage.ch: success ✅

Hooray! This Ruby can connect to drugshortage.ch. You are all set to use Bundler and RubyGems. 👌
```

**Comment by zdavatz** [comment]
the bundler version for Ruby-250 was `/usr/local/bin/gem-250 install bundler -v 1.17.3`. So after installing Ruby-250 again with the script [gen_ruby_250.txt](https://github.com/zdavatz/oddb.org/files/4741583/gen_ruby_250.txt) I needed to install the Bundler version according to the `Gemfile.lock`.
