### ISSUE TITLE
Import Swissmedic wirft folgenden Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#109]
```
Plugin: ODDB::SwissmedicPlugin

Error: RuntimeError
Message: CRITICAL: RUBYGEMS_ACTIVATION_MONITOR.owned?: before false -> after true
Backtrace:
/usr/local/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `ensure in require'
/usr/local/ruby-2.7.1/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:175:in `require'
/var/www/oddb.org/src/plugin/swissmedic.rb:293:in `update'
/var/www/oddb.org/src/util/updater.rb:406:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:508:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:404:in `update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:212:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
Alles klar, besten Dank!
