### ISSUE TITLE
Error: NoMethodError Message: undefined method `text' for #<ODDB::PatinfoDocument:0x00007f14ae2af700> Did you mean?  test

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#114]
Date: 09.07.2020, 07:27

```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `text' for #<ODDB::PatinfoDocument:0x00007f14ae2af700>
Did you mean?  test
Backtrace:
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
(eval):1:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:145:in `eval'
/var/www/oddb.org/src/plugin/text_info.rb:145:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:257:in `update_fachinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1277:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1480:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:549:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:505:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:543:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:209:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
1. First run of `jobs/import_daily` fails.
2. Second of `jobs/import_daily` run works.
