### ISSUE TITLE
error handling content-encoding gzip: buffer error (Zlib::BufError)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#115]
```
Plugin: ODDB::TextInfoPlugin

Error: Mechanize::Error
Message: error handling content-encoding gzip: buffer error (Zlib::BufError)
Backtrace:
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:843:in `rescue in response_content_encoding'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:840:in `response_content_encoding'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:296:in `fetch'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize.rb:1323:in `post_form'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize.rb:584:in `submit'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:271:in `submit'
/var/www/oddb.org/src/plugin/text_info.rb:766:in `block in swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:757:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:757:in `swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:795:in `block in textinfo_swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:794:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:794:in `textinfo_swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:1463:in `block in import_swissmedicinfo'
```

**Comment by zdavatz** [comment]
obiger Error ist heute wieder aufgetreten:
```
Plugin: ODDB::TextInfoPlugin

Error: Mechanize::Error
Message: error handling content-encoding gzip: buffer error (Zlib::BufError)
Backtrace:
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:843:in `rescue in response_content_encoding'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:840:in `response_content_encoding'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:296:in `fetch'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize.rb:1323:in `post_form'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize.rb:584:in `submit'
/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/gems/mechanize-2.7.6/lib/mechanize/form.rb:271:in `submit'
/var/www/oddb.org/src/plugin/text_info.rb:766:in `block in swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:757:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:757:in `swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:795:in `block in textinfo_swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:794:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:794:in `textinfo_swissmedicinfo_index'
/var/www/oddb.org/src/plugin/text_info.rb:1463:in `block in import_swissmedicinfo'
```

**Comment by ngiger** [comment]
Ich vermute, dass hier ein Fehler in der Datei vorliegt. Entweder wurde sie 

* nicht vollständig runtergeladen
* während des Herunterladens von swissmedic ersetzt
* irgendein UTF-8-Fehler trat auf und swissmedic hat den Fehler korrigiert, bevor der zweite Anlauf durchläuft.

Um dem auf die Spur zu kommen, müsste man diesen Fehler abfangen und die Datei auf der man arbeitet, lokal irgendwohin abspeichern. Geschätzter Aufwand 1 - 4h.

**Comment by zdavatz** [comment]
Das Interessante ist eben, wenn man den Job ein zweites Mal laufen lässt, dann klappt es. Ev. könnte man es auch mit einer gzip Validierung oder ähnlich versuchen.
