### ISSUE TITLE
ODDB::EphaInteractionPlugin - Message: 503 Backend is unhealthy

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#116]
```
Plugin: ODDB::EphaInteractionPlugin

Error: OpenURI::HTTPError
Message: 503 Backend is unhealthy
Backtrace:
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:387:in `open_http'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:764:in `buffer_open'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
/u
sr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:744:in `open'
/usr/local/ruby-2.7.1/lib/ruby/2.7.0/open-uri.rb:50:in `open'
/var/www/oddb.org/src/util/latest.rb:21:in `fetch_with_http'
/var/www/oddb.org/src/util/latest.rb:40:in `get_latest_file'
/var/www/oddb.org/src/plugin/epha_interactions.rb:40:in `update'
/var/www/oddb.org/src/util/updater.rb:530:in `update_immediate_with_error_report'
/var/www/oddb.org/src/util/updater.rb:374:in `update_epha_interactions'
/var/www/oddb.org/src/util/updater.rb:200:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```
I guess this comes from github.

**Comment by ngiger** [comment]
I think this is a temporary problem. On thinpower I did run `sudo -u apache /usr/local/bin/bundle-271 exec /usr/local/bin/ruby-271 jobs/update_epha_interactions` in `/var/www/oddb.org` in the screen import_epha and it completed without any problem.
Lets wait to see whether the problem shows up again in the next few days.

**Comment by zdavatz** [comment]
I think so as well.
