### ISSUE TITLE
Fix parsing FI/PI under Ruby 3.0

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb.org#120]
The unit tests under Ruby 3.0 for ext/fiparse throw a lot of errors.
Most stem from the fact, that tables are not correctly handled.

**Comment by ngiger** [comment]
After fixing one erro in ext/fiparse/src/textinfo_hpricot.rbr via commit 4a3de719554e06295f020766a7ce3f03e732873a, running import_daily could update over 1670 fachinfo. However it errored with the following stacktrace

> Error: NoMethodError
Message: undefined method `text' for #<ODDB::PatinfoDocument:0x0000558de9aa9cf0 @iksnrs=#<ODBA::Stub:9674680#39162757 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @name=#<ODBA::Stub:9674700#39162758 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @company=#<ODBA::Stub:9674720#39162759 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @galenic_form=nil, @effects=#<ODBA::Stub:9674740#39162760 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @amendments=#<ODBA::Stub:9674760#39162761 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @contra_indications=#<ODBA::Stub:9674780#39162762 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @precautions=#<ODBA::Stub:9674800#39162763 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @pregnancy=#<ODBA::Stub:9674820#39162764 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @usage=#<ODBA::Stub:9674840#39162765 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @unwanted_effects=#<ODBA::Stub:9674860#39162766 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @general_advice=#<ODBA::Stub:9674880#39162767 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @composition=#<ODBA::Stub:9674900#39162768 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @packages=#<ODBA::Stub:9674920#39162769 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @distribution=nil, @fabrication=nil, @date=#<ODBA::Stub:9674940#39162770 @odba_class=ODDB::Text::Chapter @odba_container=9674600#38363236>, @odba_id=38363236, @odba_persistent=true, @odba_observers=[], @revision=2018-06-01 07:47:31.097304108 +0200, @oid=38363236>
Did you mean?  test
Backtrace:
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
(eval):1:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:145:in `eval'
/var/www/oddb.org/src/plugin/text_info.rb:145:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:257:in `update_fachinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1277:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1480:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1479:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:549:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:505:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:543:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:209:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>

**Comment by ngiger** [comment]
Aufwand war:
11.1.21 3.5h 
20.1.21 1h
21.1.21 1.5h

**Comment by ngiger** [comment]
Spec und unit-tests laufen jetzt durch
