### ISSUE TITLE
Suche nach ZI "Spirig" wirft einen Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#136]
1. Suche nach "ZI" wählen.
2. Nach "Spirig" suchen.
3. Folgender Error kommt:
![Bildschirmfoto 2021-04-19 um 16 47 11](https://user-images.githubusercontent.com/4953/115255754-dd66c700-a12e-11eb-9665-0f02e6c772cb.png)
4. Es wäre **nützlich** wenn bei diesem Error die Registrations-Nummer angezeigt wird.

**Comment by zdavatz** [comment]
Versuche jetzt: `sudo -u apache bundle-300 exec ruby-300 jobs/update_textinfo_swissmedicinfo --no-download --target=pi Spirig --reparse`

**Comment by zdavatz** [comment]
Resultiert in:
```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `downcase' for ["Spirig"]:Array
Backtrace:
/var/www/oddb.org/src/plugin/text_info.rb:1406:in `block in parse_aips_download'
/var/www/oddb.org/src/plugin/text_info.rb:1375:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1375:in `parse_aips_download'
/var/www/oddb.org/src/plugin/text_info.rb:1464:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:548:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:504:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:542:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:328:in `update_textinfo_swissmedicinfo'
jobs/update_textinfo_swissmedicinfo:39:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/update_textinfo_swissmedicinfo:12:in `<module:Util>'
jobs/update_textinfo_swissmedicinfo:11:in `<module:ODDB>'
jobs/update_textinfo_swissmedicinfo:10:in `<main>'
```

**Comment by zdavatz** [comment]
Ok, wenn ich 
```
sudo -u apache bundle-300 exec ruby-300 jobs/update_textinfo_swissmedicinfo --no-download --target=both 12806 14991 27821 30145 33667 34040 34096 38459 38782 38840 39474 39639 39640 42647 42863 44000 45114 45323 46861 46863 47314 47315 47596 48205 48869 49379 50964 53698 53891 53917 53998 54450 55183 55375 55521 55875 55922 55926 56241 56344 56722 56900 56903 57056 57135 57186 57262 57452 57457 57623 57634 57755 57770 57962 57963 57979 58036 58122 58285 58463 58485 58486 58530 58593 58642 58862 58941 59132 59351 59813 60020 60134 60485 61209 61376 61393 62142 62147 62149 62293 62301 62302 62304 62410 62468 62568 62743 62789 62790 62796 62798 62799 62817 62829 62898 62899 62900 62920 62934 62987 63013 63030 63059 63077 63119 63175 63176 63179 63201 63220 63235 65088 65219 65234 65239 65262 65263 65280 65383 65441 65455 65456 65476 65795 65828 65842 65860 65877 65885 65908 65930 65931 66003 66009 66013 66014 66071 66089 66096 66097 66155 66203 66233 66239 66256 66260 66341 66373 66426 66429 66463 66474 66512 66519 66520 66557 66559 66561 66569 66594 66599 66612 66683 66700 66701 66711 66744 66818 66875 66903 66949 66970 66972 66974 66994 67096 67130 67155 67169 67180 67227 67240 67241 67362 67421 67423 67447 67466 67495 67496 67511 67553 67559 67561 67574 67624 67625 67641 67654 67675 67685 67753 67808 67973 68090 68105 68242 68273 --reparse
```
kommt
```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `delete' for #<ODDB::PatinfoDocument:0x00007fd429087b18 @iksnrs=#<ODBA::Stub:6734000#47748105 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @name=#<ODBA::Stub:6734020#47748106 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @company=#<ODBA::Stub:6734040#47748107 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @galenic_form=nil, @effects=#<ODBA::Stub:6734060#47748108 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @amendments=#<ODBA::Stub:6734080#47748109 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @contra_indications=#<ODBA::Stub:6734100#47748110 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @precautions=#<ODBA::Stub:6734120#47748111 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @pregnancy=#<ODBA::Stub:6734140#47748112 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @usage=#<ODBA::Stub:6734160#47748113 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @unwanted_effects=#<ODBA::Stub:6734180#47748114 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @general_advice=#<ODBA::Stub:6734200#47748115 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @composition=nil, @packages=#<ODBA::Stub:6734220#47748116 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @distribution=nil, @fabrication=nil, @date=#<ODBA::Stub:6734240#47748117 @odba_class=ODDB::Text::Chapter @odba_container=6733980#47434581>, @odba_id=47434581, @odba_persistent=true, @odba_observers=[], @revision=2021-04-02 07:53:35.290246881 +0200, @oid=47434581>
Backtrace:
/var/www/oddb.org/src/plugin/text_info.rb:307:in `rescue in store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:299:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:341:in `store_patinfo_for_all_packages'
/var/www/oddb.org/src/plugin/text_info.rb:374:in `block in update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:373:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:373:in `update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1294:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1488:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1487:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1487:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:548:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:504:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:542:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:328:in `update_textinfo_swissmedicinfo'
jobs/update_textinfo_swissmedicinfo:39:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/update_textinfo_swissmedicinfo:12:in `<module:Util>'
jobs/update_textinfo_swissmedicinfo:11:in `<module:ODDB>'
jobs/update_textinfo_swissmedicinfo:10:in `<main>'
```

**Comment by zdavatz** [comment]
Das Problem scheint hier zu liegen:
```
/var/www/oddb.org/src/plugin/text_info.rb:1294:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1488:in `block in import_swissmedicinfo'
Delete lang de patinfo NoMethodError 67241/01/001: de Co-Amoxicillin Spirig HC® Filmtabletten
```

**Comment by zdavatz** [comment]
Der geht nicht:
```
sudo -u apache bundle-300 exec ruby-300 jobs/update_textinfo_swissmedicinfo --no-download --target=pi 67240 --reparse
```

**Comment by zdavatz** [comment]
```
sudo -u apache bundle-300 exec ruby-300 jobs/update_textinfo_swissmedicinfo --no-download --target=pi 67241 --reparse
```
results in
```
Descriptions.description error
/var/www/oddb.org/src/util/language.rb:29:in `description'
/var/www/oddb.org/src/util/language.rb:54:in `method_missing'
(eval):1:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:300:in `eval'
/var/www/oddb.org/src/plugin/text_info.rb:300:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:341:in `store_patinfo_for_all_packages'
/var/www/oddb.org/src/plugin/text_info.rb:374:in `block in update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:373:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:373:in `update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1294:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1488:in `block in import_swissmedicinfo'
Delete lang de patinfo NoMethodError 67241/01/001: de Co-Amoxicillin Spirig HC® Filmtabletten
```

**Comment by zdavatz** [comment]
Das klappt auch nicht.
```
ywesee@thinpower /var/www/oddb.org $ /usr/local/bin/ruby-300 bin/admin
ch.oddb> update @system.registration('67241').pointer, :patinfo => nil
-> #<ODDB::Registration:0x00007fd9b79f5388>
ch.oddb> update @system.registration('67240').pointer, :patinfo => nil
-> #<ODDB::Registration:0x00007fd99095ad50>
ch.oddb>
```

**Comment by zdavatz** [comment]
Jetzt klappt: https://ch.oddb.org/de/gcc/patinfo/reg/67240/seq/01/pack/001
