### ISSUE TITLE
Import_Daily wirft `undefined method size' for` Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#138]
`Import_Daily` wirft heute diesen Error
```
Error: NoMethodError
Message: undefined method `size' for #<ODDB::PatinfoDocument:0x00007f3f35052370 @iksnrs=#<ODBA::Stub:8483400#42501786 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @name=#<ODBA::Stub:8483420#42501787 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @company=#<ODBA::Stub:8483440#42501788 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @galenic_form=nil, @effects=#<ODBA::Stub:8483460#42501789 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @amendments=nil, @contra_indications=#<ODBA::Stub:8483480#42501790 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @precautions=nil, @pregnancy=#<ODBA::Stub:8483500#42501791 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @usage=#<ODBA::Stub:8483520#42501792 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @unwanted_effects=#<ODBA::Stub:8483540#42501793 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @general_advice=#<ODBA::Stub:8483560#42501794 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @composition=nil, @packages=#<ODBA::Stub:8483580#42501795 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @distribution=nil, @fabrication=nil, @date=#<ODBA::Stub:8483600#42501796 @odba_class=ODDB::Text::Chapter @odba_container=8483380#42330856>, @odba_id=42330856, @odba_persistent=true, @odba_observers=[], @revision=2019-06-22 07:51:54.132653143 +0200, @oid=42330856>
Backtrace:
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/src/plugin/text_info.rb:286:in `store_patinfo_change_diff'
/var/www/oddb.org/src/plugin/text_info.rb:316:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:341:in `store_patinfo_for_all_packages'
/var/www/oddb.org/src/plugin/text_info.rb:374:in `block in update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:373:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:373:in `update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1294:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1488:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1487:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1487:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:548:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:504:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:542:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:328:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:209:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```
der hängt wohl damit zusammen #137

**Comment by zdavatz** [comment]
Second try worked.
