### ISSUE TITLE
Another import_daily Error related to #137 and #138

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#140]
```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `text' for #<ODDB::PatinfoDocument:0x00007fab54a7bbb8 @iksnrs=#<ODBA::Stub:4415120#39386025 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @name=#<ODDB::Text::Chapter:0x00007fab54658ab8 @sections=[], @heading="Co-Amoxicillin Axapharm, Filmtabletten", @odba_id=39386026, @odba_persistent=true, @odba_observers=[]>, @company=#<ODBA::Stub:4415140#39386027 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @galenic_form=nil, @effects=#<ODBA::Stub:4415160#39386028 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @amendments=#<ODBA::Stub:4415180#39386029 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @contra_indications=#<ODBA::Stub:4415200#39386030 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @precautions=nil, @pregnancy=#<ODBA::Stub:4415220#39386031 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @usage=#<ODBA::Stub:4415240#39386032 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @unwanted_effects=#<ODDB::Text::Chapter:0x00007fab5460bfb0 @sections=[#<ODDB::Text::Section:0x00007fab5460bee8 @subheading="", @paragraphs=[#<ODDB::Text::Paragraph:0x00007fab5460bdd0 @preformatted=false, @text="Gastrointestinale St\u00F6rungen wie Magenbeschwerden oder \u00DCbelkeit. Ebenfalls vorkommen k\u00F6nnen Reaktionen wie Brechreiz, Appetitlosigkeit, Bl\u00E4hungen, Erbrechen, Durchfall, weicher Stuhl, Dyspepsie, Bauchschmerzen und Entz\u00FCndung der Zunge oder der Mundschleimhaut.", @formats=[#<ODDB::Text::Format:0x00007fab5460bc90 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460bc90 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460bb78 @preformatted=false, @text="Wenn Co-Amoxicillin Axapharm zu Beginn der Mahlzeiten eingenommen wird, sind Magen-Darm-Beschwerden weniger h\u00E4ufig.", @formats=[#<ODDB::Text::Format:0x00007fab5460bb00 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460bb00 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460bab0 @preformatted=false, @text="Allergische Reaktionen sind mit Co-Amoxicillin Axapharm h\u00E4ufig, wie bei allen Arzneimitteln der Gruppe der Penicilline.", @formats=[#<ODDB::Text::Format:0x00007fab5460ba38 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460ba38 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b9e8 @preformatted=false, @text="Hautausschl\u00E4ge, Hautr\u00F6tungen, Juckreiz und Urtikaria (Nesselsucht) k\u00F6nnen auftreten.", @formats=[#<ODDB::Text::Format:0x00007fab5460b970 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b970 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b920 @preformatted=false, @text="Ebenfalls k\u00F6nnen Pilzinfektionen der Haut/Schleimh\u00E4ute auftreten.", @formats=[#<ODDB::Text::Format:0x00007fab5460b8a8 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b8a8 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b858 @preformatted=false, @text="Gelegentlich k\u00F6nnen Schwindelgef\u00FChl und Kopfschmerzen auftreten.", @formats=[#<ODDB::Text::Format:0x00007fab5460b7e0 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b7e0 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b768 @preformatted=false, @text="Sehr selten k\u00F6nnen Hyperaktivit\u00E4t, Erregung, Angst, Schlaflosigkeit, Verwirrung, Verhaltens\u00E4nderungen, Benommenheit, Kr\u00E4mpfe und Empfindungsst\u00F6rungen auftreten.", @formats=[#<ODDB::Text::Format:0x00007fab5460b6f0 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b6f0 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b6a0 @preformatted=false, @text="Selten stellte man oberfl\u00E4chliche Zahnverf\u00E4rbungen fest. Diese Erscheinung verschwindet gew\u00F6hnlich mit dem Z\u00E4hneputzen wieder.", @formats=[#<ODDB::Text::Format:0x00007fab5460b628 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b628 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b5d8 @preformatted=false, @text="Sehr selten wurde eine dunkel belegte Zunge, Hyperkinese (\u00FCberm\u00E4ssige Bewegungsaktivit\u00E4t), Blutbildver\u00E4nderungen, Verl\u00E4ngerung der Blutungsdauer und Prothrombinzeit, Leberentz\u00FCndung (Hepatitis), Nierenentz\u00FCndung und Nierenfunktionsst\u00F6rungen beobachtet.", @formats=[#<ODDB::Text::Format:0x00007fab5460b560 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b560 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b510 @preformatted=false, @text="Bei der Verabreichung von Amoxicillin im Alter von 0-9 Monate k\u00F6nnen Zahnschmelzsch\u00E4den (z.B. weisse Streifung, Verf\u00E4rbung) der definitiven Schneidez\u00E4hne nicht ausgeschlossen werden.", @formats=[#<ODDB::Text::Format:0x00007fab5460b498 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b498 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b448 @preformatted=false, @text="\u00DCber Gelbsucht wurde selten berichtet.", @formats=[#<ODDB::Text::Format:0x00007fab5460b3d0 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b3d0 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b380 @preformatted=false, @text="Konsultieren Sie sofort Ihren Arzt bzw. Ihre \u00C4rztin beim Auftreten von:", @formats=[#<ODDB::Text::Format:0x00007fab5460b308 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b308 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b2b8 @preformatted=false, @text="-Nesselfieber, grossfl\u00E4chigem Hautausschlag, Hautr\u00F6tungen;", @formats=[#<ODDB::Text::Format:0x00007fab5460b240 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b240 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b1f0 @preformatted=false, @text="gelblicher Farbe der Haut oder des weissen Teils der Augen;", @formats=[#<ODDB::Text::Format:0x00007fab5460b178 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b178 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b128 @preformatted=false, @text="pl\u00F6tzlich einsetzenden Bauchschmerzen oder Erbrechen;", @formats=[#<ODDB::Text::Format:0x00007fab5460b0b0 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460b0b0 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460b060 @preformatted=false, @text="schweren, blutigen oder anhaltenden Durchf\u00E4llen;", @formats=[#<ODDB::Text::Format:0x00007fab5460afe8 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460afe8 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460af98 @preformatted=false, @text="-Atemproblemen in Form von Asthmaanf\u00E4llen und Heuschnupfen.", @formats=[#<ODDB::Text::Format:0x00007fab5460af20 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460af20 @end=-1, @start=0, @values=[]>>, #<ODDB::Text::Paragraph:0x00007fab5460aed0 @preformatted=false, @text="Wenn Sie Nebenwirkungen bemerken, die hier nicht beschrieben sind, sollten Sie Ihren Arzt oder Apotheker bzw. Ihre \u00C4rztin oder Apothekerin informieren.", @formats=[#<ODDB::Text::Format:0x00007fab5460ae58 @end=-1, @start=0, @values=[]>], @raw_txt=nil, @format=#<ODDB::Text::Format:0x00007fab5460ae58 @end=-1, @start=0, @values=[]>>]>], @heading="Welche Nebenwirkungen kann Co-Amoxicillin Axapharm haben?", @odba_id=39386033, @odba_persistent=true, @odba_observers=[]>, @general_advice=#<ODBA::Stub:4415260#39386034 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @composition=#<ODBA::Stub:4415280#39386035 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @packages=#<ODBA::Stub:4415300#39386036 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @distribution=nil, @fabrication=nil, @date=#<ODBA::Stub:4415320#39386037 @odba_class=ODDB::Text::Chapter @odba_container=4409140#38363634>, @odba_id=38363634, @odba_persistent=true, @odba_observers=[], @change_log=#<ODBA::Stub:4415340#39622190 @odba_class=Array @odba_container=4409140#38363634>, @revision=2018-07-01 07:46:18.616601207 +0200, @oid=38363634>
Did you mean?  test
Backtrace:
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
(eval):1:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:147:in `eval'
/var/www/oddb.org/src/plugin/text_info.rb:147:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:265:in `update_fachinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1286:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1489:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1488:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1488:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:537:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:493:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:531:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:209:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
running "import_daily" again helped.
