### ISSUE TITLE
FATAL:  sorry, too many clients already (DBI::OperationalError)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#141]
Getting this error again #97
```
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/pg/database.rb:83:in `rescue in initialize': FATAL:  sorry, too many clients already (DBI::OperationalError)
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/pg/database.rb:40:in `initialize'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/Pg.rb:157:in `new'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/Pg.rb:157:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbi-0.5.7/lib/dbi/handles/driver.rb:33:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbi-0.5.7/lib/dbi.rb:148:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:63:in `block in _connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `times'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `_connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `block in connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `synchronize'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:22:in `initialize'
        from /var/www/oddb.org/etc/db_connection.rb:10:in `new'
        from /var/www/oddb.org/etc/db_connection.rb:10:in `<top (required)>'
        from /var/www/oddb.org/src/util/job.rb:7:in `require'
        from /var/www/oddb.org/src/util/job.rb:7:in `<top (required)>'
        from jobs/import_daily:7:in `require'
        from jobs/import_daily:7:in `<main>'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/pg/database.rb:52:in `initialize': FATAL:  sorry, too many clients already (PG::ConnectionBad)
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/pg/database.rb:52:in `new'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/pg/database.rb:52:in `initialize'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/Pg.rb:157:in `new'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbd-pg-0.5.7/lib/dbd/Pg.rb:157:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbi-0.5.7/lib/dbi/handles/driver.rb:33:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbi-0.5.7/lib/dbi.rb:148:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:63:in `block in _connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `times'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `_connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `block in connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `synchronize'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `connect'
        from /var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:22:in `initialize'
        from /var/www/oddb.org/etc/db_connection.rb:10:in `new'
        from /var/www/oddb.org/etc/db_connection.rb:10:in `<top (required)>'
        from /var/www/oddb.org/src/util/job.rb:7:in `require'
        from /var/www/oddb.org/src/util/job.rb:7:in `<top (required)>'
        from jobs/import_daily:7:in `require'
        from jobs/import_daily:7:in `<main>'
```

**Comment by zdavatz** [comment]
I am also seeing this:
```
2021-11-19 07:01:37.165 CET [10025] FATAL:  sorry, too many clients already
2021-11-19 07:08:49.893 CET [11771] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:09:49.908 CET [12059] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:10:32.990 CET [2422] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:11:13.530 CET [12411] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:12:42.611 CET [12720] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:13:16.910 CET [12888] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:13:42.617 CET [13015] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:31:01.675 CET [16960] LOG:  could not receive data from client: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
2021-11-19 07:31:01.686 CET [17132] LOG:  could not receive data from client: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
2021-11-19 07:34:42.855 CET [18831] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:35:34.202 CET [18975] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:35:46.240 CET [18991] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:38:34.209 CET [19701] LOG:  using stale statistics instead of current ones because stats collector is not responding
2021-11-19 07:57:49.574 CET [9763] LOG:  could not receive data from client: Die Verbindung wurde vom Kommunikationspartner zurückgesetzt
```
