### ISSUE TITLE
Import Swissmedic Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#143]
```
Plugin: ODDB::SwissmedicPlugin

Error: NoMethodError
Message: undefined method `join' for "46240: heparinum natricum 417 U.I. corresp. natrium 0.25 mg, acidum hydrochloridum, aqua ad iniectabile q.s. ad solutionem pro 1 ml.":String
Backtrace:
/var/www/oddb.org/src/plugin/swissmedic.rb:750:in `block in report'
/var/www/oddb.org/src/plugin/swissmedic.rb:750:in `collect'
/var/www/oddb.org/src/plugin/swissmedic.rb:750:in `report'
/var/www/oddb.org/src/plugin/plugin.rb:56:in `block in log_info'
/var/www/oddb.org/src/plugin/plugin.rb:55:in `each'
/var/www/oddb.org/src/plugin/plugin.rb:55:in `inject'
/var/www/oddb.org/src/plugin/plugin.rb:55:in `log_info'
/var/www/oddb.org/src/util/updater.rb:158:in `log_info'
/var/www/oddb.org/src/util/updater.rb:394:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:493:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:389:in `update_swissmedic'
jobs/import_swissmedic:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```

**Comment by ngiger** [comment]
Pushed a fix. Now the unparsed compositions are shown in the email like this

<pre>
Unparsed compositions 649:
 00677: escherichia coli viva 15 - 45 Mio. U., natrii chloridum corresp. natrium 2.382 mg, magnesii sulfas heptahydricus, kalii chloridum, calcii chloridum dihydricum, magnesii chloridum hexahydricum, aqua purificata ad suspensionem pro 1 ml, corresp. 14 guttae.
46240: heparinum natricum 417 U.I. corresp. natrium 0.25 mg, acidum hydrochloridum, aqua ad iniectabile q.s. ad solutionem pro 1 ml.
48351: bupivacaini hydrochloridum anhydricum 2.5 mg, natrii chloridum, aqua ad iniectabile q.s. ad solutionem pro 1 ml.
48351: bupivacaini hydrochloridum anhydricum 5 mg, natrii chloridum, aqua ad iniectabile q.s. ad solutionem pro 1 ml.
48351: bupivacaini hydrochloridum anhydricum 40 mg, natrii chloridum, aqua ad iniectabile q.s. ad solutionem pro 1 ml.
60134: venlafaxinum 75 mg ut venlafaxini hydrochloridum, sacchari sphaerae corresp. saccharum 80.97 mg, hydroxypropylcellulosum, hypromellosum, talcum, ethylcellulosum, ammoniae solutio 28 per centum, dibutylis sebacas, acidum oleicum, silica colloidalis anhydrica, Kapselhülle: gelatina, natrii laurilsulfas corresp. natrium 4 µg, E 104, E 110 6 µg, E 171, pro capsula.
60134: venlafaxinum 75 mg ut venlafaxini hydrochloridum, sacchari sphaerae corresp. saccharum 80.97 mg, hydroxypropylcellulosum, hypromellosum, talcum, ethylcellulosum, ammoniae solutio 28 per centum, dibutylis sebacas, acidum oleicum, silica colloidalis anhydrica, Kapselhülle: gelatina, natrii laurilsulfas corresp. natrium 4 µg, E 104, E 110 6 µg, E 171, pro capsula.
<...>
</pre>

**Comment by zdavatz** [comment]
please reference the commit here.

**Comment by ngiger** [comment]
Job on thinpower restarted

**Comment by zdavatz** [comment]
War das der Error?
```
Plugin: ODDB::SwissmedicPlugin

Error: Interrupt
Message:
Backtrace:
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:61:in `const_get'
/usr/local/ruby-3.0.0/lib/ruby/3.0.0/delegate.rb:61:in `const_missing'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbi-0.5.7/lib/dbi/row.rb:250:in `conv_param'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/ydbi-0.5.7/lib/dbi/row.rb:170:in `[]'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/index.rb:257:in `block in update_origin'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/index.rb:255:in `each'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/index.rb:255:in `update_origin'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/index.rb:162:in `update'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/cache.rb:591:in `block in update_indices'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/cache.rb:590:in `each'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/cache.rb:590:in `update_indices'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/cache.rb:516:in `store'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/odba-1.1.6/lib/odba/persistable.rb:274:in `odba_isolated_store'
/var/www/oddb.org/src/model/registration_observer.rb:18:in `add_registration'
/var/www/oddb.org/src/model/registration.rb:324:in `replace_observer'
/var/www/oddb.org/src/model/registration.rb:308:in `company='
/var/www/oddb.org/src/util/persistence.rb:105:in `block in update_values'
/var/www/oddb.org/src/util/persistence.rb:102:in `each'
/var/www/oddb.org/src/util/persistence.rb:102:in `update_values'
/var/www/oddb.org/src/util/persistence.rb:278:in `issue_update'
/var/www/oddb.org/src/util/oddbapp.rb:135:in `block in update'
/var/www/oddb.org/src/util/failsafe.rb:10:in `failsafe'
/var/www/oddb.org/src/util/oddbapp.rb:133:in `update'
/var/www/oddb.org/src/util/oddbapp.rb:1598:in `update'
/var/www/oddb.org/src/plugin/swissmedic.rb:1260:in `update_registration'
/var/www/oddb.org/src/plugin/swissmedic.rb:1333:in `block in update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:1324:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:1324:in `each_with_index'
/var/www/oddb.org/src/plugin/swissmedic.rb:1324:in `update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:367:in `update'
/var/www/oddb.org/src/util/updater.rb:391:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:493:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:389:in `update_swissmedic'
jobs/import_swissmedic:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```

**Comment by ngiger** [comment]
Nein, mein Commit fixed the Fehler, für den issue 143 geöffnet wurde. Obiger Backtrace kommt, dass ich den Job unterbrochen habe ("Error: Interrupt"), da ich nicht alle commits geholt hatte.
