### ISSUE TITLE
Refdata companies Update no longer works

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#151]
1. Import Swissmedic Job has a follower job for Refdata companies update
2. This results in
```
Error: Savon::HTTPError
Message: HTTP error (302): <html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>

Backtrace:
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/savon-2.12.1/lib/savon/operation.rb:27:in `rescue in ensure_exists!'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/savon-2.12.1/lib/savon/operation.rb:21:in `ensure_exists!'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/savon-2.12.1/lib/savon/operation.rb:15:in `create'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/savon-2.12.1/lib/savon/client.rb:32:in `operation'
/var/www/oddb.org/vendor/bundle/ruby/3.0.0/gems/savon-2.12.1/lib/savon/client.rb:36:in `call'
/var/www/oddb.org/src/plugin/refdata_jur.rb:56:in `download_partners_xml'
/var/www/oddb.org/src/plugin/refdata_jur.rb:199:in `get_latest_file'
/var/www/oddb.org/src/plugin/refdata_jur.rb:117:in `update'
/var/www/oddb.org/src/util/updater.rb:237:in `block in update_refdata_jur'
/var/www/oddb.org/src/util/updater.rb:493:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:235:in `update_refdata_jur'
/var/www/oddb.org/src/util/updater.rb:409:in `update_swissmedic_followers'
jobs/import_swissmedic:15:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```
3. Probably related to: https://github.com/zdavatz/oddb2xml/issues/55

**Comment by ngiger** [comment]
Under https://refdatabase.refdata.ch/ one sees, that they have a new V2 services of the XSD.
Alternatively one could also download an XLSX, which has the following headers:
GLN | Status | Sprache | Name 1 | Name 2
i
Example data is:
7601001367753 | A | DE | Amavita Apotheke Vorstadt | GaleniCare AG

Until now we extracted the following fields:

- Betriebsname
- PLZ
- Ort
- GlnBetrieb
- BetriebsCodeId
- KantonsCodeId

Therefore we must use the SOAP and version V2. Looks like this is a few hours of work till we get everything working again.

**Comment by zdavatz** [comment]
1. Version 1 is still online. https://refdatabase.refdata.ch/Service/Partner.asmx
2. We just need to fix the HTTPS request.
3. This URL has to use HTTPS: https://refdatabase.refdata.ch/Service/Partner.asmx

**Comment by ngiger** [comment]
I downloaded successfully the data by:

* Create a partner.xml with the following content:
`<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ns1="http://refdatabase.refdata.ch/Partner_in" xmlns:ns2="http://refdatabase.refdata.ch/">
<SOAP-ENV:Body>
<ns2:DownloadPartnerInput>
<ns1:TYPE>ALL</ns1:TYPE>
</ns2:DownloadPartnerInput>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>
`

* Then execute the following commands:

`wget --post-file "partner.xml" --header "content-type: text/xml;charset=utf-8" --header "SOAPAction: http://refdatabase.refdata.ch/Download" https://refdatabase.refdata.ch/Service/Partner.asmx -O pe.xml`
`xmllint --format pe.xml > partner_sexy.xml`

**Comment by zdavatz** [comment]
Yes, I know, this works. Version 1 has always been there and still works. You just need to use HTTPS.

**Comment by ngiger** [comment]
Which is just an awfull mix of URLs with http and https.

**Comment by zdavatz** [comment]
Die Antwort von Refdata dazu ist:
```
"La "SOAP Action" est un identifiant de la méthode à exécuter dans le protocole soap elle est transmise comme Header HTTP, elle n'indique en aucun cas à quelle url est disponible le service, elle ne doit donc pas être modifiée

Voici ce que dit la spécification de SOAP (https://www.w3.org/TR/2000/NOTE-SOAP-20000508/#_Toc478383528)

"The SOAPAction HTTP request header field can be used to indicate the intent of the SOAP HTTP request. The value is a URI identifying the intent. SOAP places no restrictions on the format or specificity of the URI or that it is resolvable. An HTTP client MUST use this header field when issuing a SOAP HTTP Request."

Nous avons donc choisi le nom selon l'url originale comme le namespace des payloads.

Si nous changeons la valeur de la SOAP Action, tous les clients ayant implémenté l'interface vers nos services devraient faire une mise à jour."
```
