### ISSUE TITLE
Diskrepanz zwischen Med-Drugs update und RSS-Feed für Code 10 Neuzugang BAG

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#154]
1. Das Med-Drugs Update vom 1.3.2022 zeigt nur einen BAG Neuzugang an (Code 10): [med-drugs-20220301.xls](https://github.com/zdavatz/oddb.org/files/8160875/med-drugs-20220301.xls)
2. Gemäss dem RSS Feed sind es aber [49](https://ch.oddb.org/de/gcc/rss/channel/sl_introduction.rss).
3. ![latest-screenshot](https://user-images.githubusercontent.com/4953/156155233-905fca8c-1673-4122-9ccd-ed6878e8d7e1.png)
4. Im Februar 2022 gab es das gleiche Problem.
5. Das Produkt _Lenalidomid Accord 2.5 mg, Hartkapseln_ wurde am [03.02.2021](https://ch.oddb.org/de/gcc/show/reg/67714/seq/01/pack/001) von Swissmedic übernommen.
6. Am [01.03.2022](https://ch.oddb.org/de/gcc/sl_entry/reg/67714/seq/07/pack/007) erfolgte der SL Eintrag für _Lenalidomid Accord 2.5 mg, Hartkapseln_.
7. Siehe auch: https://github.com/zdavatz/oddb.org/issues/146

**Comment by zdavatz** [comment]
In der Mail vom 10.3.2022 ist nach wie vor nur ein Code 10 vorhanden.
![latest-screenshot](https://user-images.githubusercontent.com/4953/157699499-a0b94879-27b2-4207-9970-4a18920cba7e.png)

**Comment by b123400** [comment]
Wenn ich `bundler exec rackup -p 8012` laufen, es gibt der Error

```
NoMethodError at /
undefined method `sorted_fachinfos' for nil:NilClass @system.send(m, *args, &block) ^^^^^
Ruby 	/home/a/oddb.org/src/util/oddbapp.rb: in block in method_missing, line 1497
Web 	GET localhost/
Jump to:

Traceback (innermost first)

    /home/a/oddb.org/src/util/oddbapp.rb: in block in method_missing
                @system.send(m, *args, &block)...
    /home/a/oddb.org/src/util/oddbapp.rb: in synchronize
              @cache_mutex.synchronize do...
    /home/a/oddb.org/src/util/oddbapp.rb: in method_missing
              @cache_mutex.synchronize do...
    /home/a/oddb.org/src/state/drugs/init.rb: in init
            fachinfos = @session.app.sorted_fachinfos...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb: in logout
              @state.init...
    /home/a/oddb.org/src/util/session.rb: in logout
              super...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb: in block in process_rack
                  logout unless @active_state...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb: in synchronize
              html = @mutex.synchronize do...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/session.rb: in process_rack
              html = @mutex.synchronize do...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/sbsm-1.6.0/lib/sbsm/app.rb: in call
              res = session.process_rack(rack_request: request)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/lint.rb: in _call
              ary = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/lint.rb: in call
              dup._call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb: in call
              @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/content_length.rb: in call
              status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/static.rb: in call
                @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb: in call
              status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb: in call
              status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb: in call
              status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/lint.rb: in _call
              ary = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/lint.rb: in call
              dup._call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/show_exceptions.rb: in call
              @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/common_logger.rb: in call
              status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/content_length.rb: in call
              status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/rack-2.2.3/lib/rack/handler/webrick.rb: in service
                status, headers, body = @app.call(env)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb: in service
              si.service(req, res)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/httpserver.rb: in run
                  server.service(req, res)...
    /home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/webrick-1.7.0/lib/webrick/server.rb: in block in start_thread
                  block ? block.call(sock) : run(sock)

$ bundler exec ruby jobs/import_bsv
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Attention: monkey-patching CSV::Cell
racc/parser.rb:189: warning: already initialized constant Racc::Parser::Racc_Runtime_Version
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:188: warning: previous definition of Racc_Runtime_Version was here
racc/parser.rb:192: warning: already initialized constant Racc::Parser::Racc_Runtime_Core_Version_R
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:189: warning: previous definition of Racc_Runtime_Core_Version_R was here
racc/parser.rb:205: warning: already initialized constant Racc::Parser::Racc_Main_Parsing_Routine
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:207: warning: previous definition of Racc_Main_Parsing_Routine was here
racc/parser.rb:206: warning: already initialized constant Racc::Parser::Racc_YY_Parse_Method
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:208: warning: previous definition of Racc_YY_Parse_Method was here
racc/parser.rb:207: warning: already initialized constant Racc::Parser::Racc_Runtime_Core_Version
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:209: warning: previous definition of Racc_Runtime_Core_Version was here
racc/parser.rb:209: warning: already initialized constant Racc::Parser::Racc_Runtime_Type
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:210: warning: previous definition of Racc_Runtime_Type was here
/home/a/oddb.org/src/view/drugs/resultlist.rb:25: warning: already initialized constant HtmlGrid::List::BACKGROUND_SUFFIX
/home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/htmlgrid-1.2.2/lib/htmlgrid/list.rb:34: warning: previous definition of BACKGROUND_SUFFIX was here
2022-03-12 07:27:33 -0800: /home/a/oddb.org/src/util/job.rb:35:in `run': /home/a/oddb.org/log/job.pid is created (pid is 2700)
NOTICE:  table "oddb_persistence_pointer" does not exist, skipping
NOTICE:  table "oddb_package_pharmacode" does not exist, skipping
NOTICE:  table "oddb_package_name_with_size" does not exist, skipping
NOTICE:  table "oddb_commercialform_name" does not exist, skipping
NOTICE:  table "oddb_indextherapeuticus_code" does not exist, skipping
NOTICE:  table "oddb_galenicform_name" does not exist, skipping
NOTICE:  table "oddb_minifi_publication_date" does not exist, skipping
2022-03-12 07:27:33 -0800: /home/a/oddb.org/src/util/oddbapp.rb:1467:in `initialize': process: jobs/import_bsv server_uri druby://127.0.0.1:10000  auxiliary true after 0.000105417 seconds
2022-03-12 07:27:33 -0800: /home/a/oddb.org/src/util/oddbapp.rb:1493:in `rescue in initialize': Error initializing Default GalenicGroup has illegal Object ID (9) with @@primary_server 
/home/a/oddb.org/log/job.pid is deleted
/home/a/oddb.org/src/util/oddbapp.rb:1509:in `create': undefined method `execute_command' for nil:NilClass (NoMethodError)

			@system.execute_command(CreateCommand.new(pointer))
			       ^^^^^^^^^^^^^^^^
	from /home/a/oddb.org/src/util/updater.rb:267:in `update_bsv'
	from jobs/import_bsv:14:in `block in <module:Util>'
	from /home/a/oddb.org/src/util/job.rb:41:in `run'
	from jobs/import_bsv:12:in `<module:Util>'
	from jobs/import_bsv:11:in `<module:ODDB>'
	from jobs/import_bsv:10:in `<main>'
```

Diese ist der Log:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
2022-03-12 08:06:35 -0800 Starting /home/a/.rbenv/versions/3.1.1/bin/rackup
Attention: monkey-patching CSV::Cell
2022-03-12 08:06:41 -0800: /home/a/oddb.org/src/util/oddbapp.rb:1467:in `initialize': process: /home/a/.rbenv/versions/3.1.1/bin/rackup server_uri druby://127.0.0.1:10000  auxiliary  after 6.0539e-05 seconds
2022-03-12 08:06:41 -0800: /home/a/oddb.org/src/util/oddbapp.rb:1493:in `rescue in initialize': Error initializing Default GalenicGroup has illegal Object ID (17) with @@primary_server 
127.0.0.1 - - [12/Mar/2022:08:06:52 -0800] "GET http://localhost:8012/ HTTP/1.1" 500 77997
```

-----

Wenn ich `bundler exec ruby jobs/import_bsv` laufen, es gibt der Error:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Attention: monkey-patching CSV::Cell
racc/parser.rb:189: warning: already initialized constant Racc::Parser::Racc_Runtime_Version
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:188: warning: previous definition of Racc_Runtime_Version was here
racc/parser.rb:192: warning: already initialized constant Racc::Parser::Racc_Runtime_Core_Version_R
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:189: warning: previous definition of Racc_Runtime_Core_Version_R was here
racc/parser.rb:205: warning: already initialized constant Racc::Parser::Racc_Main_Parsing_Routine
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:207: warning: previous definition of Racc_Main_Parsing_Routine was here
racc/parser.rb:206: warning: already initialized constant Racc::Parser::Racc_YY_Parse_Method
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:208: warning: previous definition of Racc_YY_Parse_Method was here
racc/parser.rb:207: warning: already initialized constant Racc::Parser::Racc_Runtime_Core_Version
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:209: warning: previous definition of Racc_Runtime_Core_Version was here
racc/parser.rb:209: warning: already initialized constant Racc::Parser::Racc_Runtime_Type
/home/a/.rbenv/versions/3.1.1/lib/ruby/3.1.0/racc/parser.rb:210: warning: previous definition of Racc_Runtime_Type was here
/home/a/oddb.org/src/view/drugs/resultlist.rb:25: warning: already initialized constant HtmlGrid::List::BACKGROUND_SUFFIX
/home/a/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/htmlgrid-1.2.2/lib/htmlgrid/list.rb:34: warning: previous definition of BACKGROUND_SUFFIX was here
2022-03-12 07:27:33 -0800: /home/a/oddb.org/src/util/job.rb:35:in `run': /home/a/oddb.org/log/job.pid is created (pid is 2700)
NOTICE:  table "oddb_persistence_pointer" does not exist, skipping
NOTICE:  table "oddb_package_pharmacode" does not exist, skipping
NOTICE:  table "oddb_package_name_with_size" does not exist, skipping
NOTICE:  table "oddb_commercialform_name" does not exist, skipping
NOTICE:  table "oddb_indextherapeuticus_code" does not exist, skipping
NOTICE:  table "oddb_galenicform_name" does not exist, skipping
NOTICE:  table "oddb_minifi_publication_date" does not exist, skipping
2022-03-12 07:27:33 -0800: /home/a/oddb.org/src/util/oddbapp.rb:1467:in `initialize': process: jobs/import_bsv server_uri druby://127.0.0.1:10000  auxiliary true after 0.000105417 seconds
2022-03-12 07:27:33 -0800: /home/a/oddb.org/src/util/oddbapp.rb:1493:in `rescue in initialize': Error initializing Default GalenicGroup has illegal Object ID (9) with @@primary_server 
/home/a/oddb.org/log/job.pid is deleted
/home/a/oddb.org/src/util/oddbapp.rb:1509:in `create': undefined method `execute_command' for nil:NilClass (NoMethodError)

			@system.execute_command(CreateCommand.new(pointer))
			       ^^^^^^^^^^^^^^^^
	from /home/a/oddb.org/src/util/updater.rb:267:in `update_bsv'
	from jobs/import_bsv:14:in `block in <module:Util>'
	from /home/a/oddb.org/src/util/job.rb:41:in `run'
	from jobs/import_bsv:12:in `<module:Util>'
	from jobs/import_bsv:11:in `<module:ODDB>'
	from jobs/import_bsv:10:in `<main>'
```

**Comment by zdavatz** [comment]
Du kannst die DB von hier runterladen: https://drive.google.com/file/d/1LrayrUOE7DhxEB3gFxfByt72qsQ-3spP/view?usp=drivesdk

**Comment by b123400** [comment]
Ich habe einer Error mit die Datei:

```
$ zcat ~/22_00-postgresql_database-ch_oddb-backup.bz2 | psql -U postgres oddb_dot_org
gzip: /home/a/22_00-postgresql_database-ch_oddb-backup.bz2: not in gzip format
```

**Comment by zdavatz** [comment]
Ah, ich denke Du musst zuerst ins `22_00-postgresql_database-ch_oddb-backup.sql.gz ` umwandeln mit `tar -xf 22_00-postgresql_database-ch_oddb-backup.bz2`. Klappt es dann?

**Comment by zdavatz** [comment]
Es sieht so aus, als würde das Problem seit Juni 2021 bestehen.

**Comment by zdavatz** [comment]
Es sieht so aus, als würden die Unregelmässigkeiten aus den ausserordentlichen SL Publikationen entstehen.
![latest-screenshot](https://user-images.githubusercontent.com/4953/159657437-8bd3506f-54c3-4e6d-bc48-0e3910248346.png)

**Comment by zdavatz** [comment]
Offenbar wird der RSS-Flag Flag für den SL-Neuzugang anders gesetzt als der SL-Neuzugangs-Flag für das Med-Drugs-Update.

**Comment by zdavatz** [comment]
Codes 10, 13 and 15 where not reported correctly in the file of May 2022.
