### ISSUE TITLE
Import daily throws errors after upgrade to Ruby 3.1.1.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#155]
1. Running Import_Daily results in
2. ![latest-screenshot](https://user-images.githubusercontent.com/4953/161002604-3508f80d-568f-43ff-9271-ad548cd01647.png)
3. ![latest-screenshot](https://user-images.githubusercontent.com/4953/161003603-2db67f1e-d1b9-4abd-926d-f6b38864c7dc.png)

**Comment by ngiger** [comment]
Auf thinpower alles auf 300 zurückgesetzt. Dazu

* cd /var/www/oddb.org; git reset --hard f7f1fb3d302c8c25f24d345db4d65bc49e453293; bundle-300 install
* in /etc/crontab alle 311 durch 300 ersetzt
* in /services/ch.oddb*/run alle 311 durch 300 ersetzt

Ein bundle-300 update nokogiri in /var/www/oddb.org schlug fehl.

Import-daily neu gestartet.

**Comment by zdavatz** [comment]
With Ruby 3.0.0 we see a lot of:
![latest-screenshot](https://user-images.githubusercontent.com/4953/161016387-5a620bee-10a0-4222-b73a-fd51a7e3ca41.png)

**Comment by zdavatz** [comment]
@ngiger `import_daily` still throws this error:
```
.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker.rb:29:in `make'
/var/www/oddb.org/src/view/rss/fachinfo.rb:75:in `to_html'
/var/www/oddb.org/src/plugin/plugin.rb:99:in `block (2 levels) in update_rss_feeds'
/var/www/oddb.org/src/plugin/plugin.rb:98:in `open'
/var/www/oddb.org/src/plugin/plugin.rb:98:in `block in update_rss_feeds'
/var/www/oddb.org/src/plugin/plugin.rb:51:in `block in l10n_sessions'
/var/www/oddb.org/src/plugin/plugin.rb:48:in `each_key'
/var/www/oddb.org/src/plugin/plugin.rb:48:in `l10n_sessions'
/var/www/oddb.org/src/plugin/plugin.rb:89:in `update_rss_feeds'
/var/www/oddb.org/src/plugin/text_info.rb:117:in `postprocess'
/var/www/oddb.org/src/plugin/text_info.rb:1504:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:537:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:493:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:531:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:209:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
Also, this is still happening:
```
ERROR:  index row size 3048 exceeds maximum 2712 for index "search_term_fachinfo_name_fr"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
DBI::ProgrammingError: ERROR:  index row size 3048 exceeds maximum 2712 for index "search_term_fachinfo_name_fr"
HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
Consider a function index of an MD5 hash of the value, or use full text indexing.
 when updating index 'fachinfo_name_fr' with a ODDB::Fachinfo
["/var/www/oddb.org/vendor/ruby/3.1.0/gems/ydbd-pg-0.5.8/lib/dbd/pg/statement.rb:62:in `rescue in execute'", "/var/www/oddb.org/vendor/ruby/3.1.0/gems/ydbd-pg-0.5.8/lib/dbd/pg/statement.rb:35:in `execute'", "/var/www/oddb.org/vendor/ruby/3.1.0/gems/ydbi-0.5.8/lib/dbi/base_classes/database.rb:96:in `execute'", "/var/www/oddb.org/vendor/ruby/3.1.0/gems/ydbi-0.5.8/lib/dbi/base_classes/database.rb:114:in `do'"]
[...]
```

**Comment by zdavatz** [comment]
weitere ODBA errors:
```
OdbaError
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:27:in `is_a?'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:88:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `block in to_html'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError
Descriptions.description error
OdbaError
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:27:in `is_a?'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:88:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `block in to_html'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError
Descriptions.description error
OdbaError
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:27:in `is_a?'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/util/language.rb:37:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:88:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `block in to_html'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError
```

**Comment by ngiger** [comment]
Content in import_daily @.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'@ was added by myself to see, where RSS-feeds got started, when we had trouble. Now, that I am sure where they come from, I will eliminated this statement to clean up the import-daily log

**Comment by zdavatz** [comment]
Was ist mit dem `odba` Error?

**Comment by ngiger** [comment]
Das sind Fehler, die von der Reperatur der fehlerhaften PI/FI herrühren. Heute sollten die fehlerhaften  korrigiert sein. Falls morgen noch solche zu finden sein, werde ich diesen nachgehen?

**Comment by zdavatz** [comment]
```
OdbaError
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:27:in `is_a?'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:88:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `block in to_html'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:439:in `make'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/rss-0.2.9/lib/rss/maker/base.rb:403:in `make'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError
Descriptions.description error
OdbaError
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:27:in `is_a?'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:88:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `block in to_html'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError
Descriptions.description error
OdbaError
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:27:in `is_a?'
/var/www/oddb.org/src/util/language.rb:34:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/util/language.rb:37:in `description'
/var/www/oddb.org/src/util/language.rb:58:in `method_missing'
/var/www/oddb.org/src/model/fachinfo.rb:79:in `localized_name'
/var/www/oddb.org/vendor/ruby/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/view/rss/fachinfo.rb:88:in `block (2 levels) in to_html'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `each'
/var/www/oddb.org/src/view/rss/fachinfo.rb:87:in `block in to_html'
ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError
Descriptions.description error
```
ODBA Errors kommen immer noch.

**Comment by ngiger** [comment]
Das sind Fehler, die von der Reperatur der fehlerhaften PI/FI herrühren. Heute sollten die fehlerhaften korrigiert werden.
Da der import_daily aber nicht durchgelaufen ist kommen die weiter, mindestens bis er mal fertig ist.

Der Import-Daily wurde abgebrochen. Weiss nicht wie es passiert ist. Hast Du ihn abgebrochen oder habe ich den Screen nicht korrekt verlassen?

**Comment by ngiger** [comment]
Diese Fehler führen nicht zum Abbruch, können aber ohne grössere Umbauten NICHT aus dem log herausgenommen werden.

**Comment by zdavatz** [comment]
Ich habe abgebrochen. Startest Du wieder neu?

**Comment by ngiger** [comment]
Habe ich schon um 12:02 neu gestartet

**Comment by zdavatz** [comment]
ok, dann dauert er viel zu lange!

**Comment by ngiger** [comment]
Nach dem Patch [Remove time consuming odba_store while creating RSS feeds](https://github.com/ngiger/oddb.org/commit/dc375fa305ef5c14743a2f2f3797f68be1c90822) lief bei mir der import_daily in 37 Minuten durch.
Anpassungen auf thinpower geholt. Morgen sollte das also besser ausschauen.
Es gab aber noch 324 Vorkommnisse von `ODBA::Stub was unable to replace ODDB::SimpleLanguage::Descriptions#30593148 from ODDB::Fachinfo:#30593146. raise OdbaError`. 
Ich schaue mal, ob ich diese description löschen kann und dann der Import-Daily bei mir durchläuft

**Comment by ngiger** [comment]
Diese ODBA-Fehler haben wir seit 2014. S.a. https://dev.ywesee.com/Niklaus/20140210-pgdg-db-preprared-statement-error

**Comment by zdavatz** [comment]
ok, warten wir morgen ab.

**Comment by zdavatz** [comment]
> Man könnte diesen Fehler allenfalls umgehen, wenn man nur die aktiven fachinfos für die RSS-Feeds berücksichtigt.

Ok, halten wir das mal im Auge.
