### ISSUE TITLE
`jobs/import _daily` results in Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#161]
1. Running `jobs/import _daily` results in Error
2. 
```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `push' for #<ODDB::PatinfoDocument:0x00007fb0cac5e590 @iksnrs=#<ODBA::Stub:4770540#39403591 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @name=#<ODBA::Stub:4770560#39403592 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @company=#<ODBA::Stub:4770580#39403593 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @galenic_form=nil, @effects=#<ODBA::Stub:4770600#39403594 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @amendments=#<ODBA::Stub:4770620#39403595 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @contra_indications=#<ODBA::Stub:4770640#39403596 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @precautions=#<ODBA::Stub:4770660#39403597 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @pregnancy=#<ODBA::Stub:4770680#39403598 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @usage=#<ODBA::Stub:4770700#39403599 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @unwanted_effects=#<ODBA::Stub:4770720#39403600 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @general_advice=#<ODBA::Stub:4770740#39403601 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @composition=#<ODBA::Stub:4770760#39403602 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @packages=#<ODBA::Stub:4770780#39403603 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @distribution=nil, @fabrication=nil, @date=#<ODBA::Stub:4770800#39403604 @odba_class=ODDB::Text::Chapter @odba_container=4766260#38363678>, @odba_id=38363678, @odba_persistent=true, @odba_observers=[], @odba_prefetch=nil, @revision=2018-07-04 07:50:18.056638039 +0200, @oid=38363678>

     self.change_log.push(item)
                    ^^^^^
Backtrace:
/var/www/oddb.org/src/model/fachinfo.rb:192:in `add_change_log_item'
/var/www/oddb.org/src/plugin/text_info.rb:167:in `store_fachinfo'
/var/www/oddb.org/src/plugin/text_info.rb:271:in `update_fachinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1296:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1499:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1498:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1498:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:537:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:493:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:531:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:209:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
Running `jobs/import_daily` again then works. Why does this not always work in the first run?
