### ISSUE TITLE
Ubuntu setup `bundle exec rackup -p 8012 --quiet` problem

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#183]
1. This command
2. `cd /var/www/oddb.org`
3. `bundle exec rackup -p 8012 --quiet`
4. Results in
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
2022-12-14 07:34:00 +0000 Starting /home/zdavatz/.rbenv/versions/3.1.1/bin/rackup
Attention: monkey-patching CSV::Cell
2022-12-14 07:34:02 +0000: /var/www/oddb.org/ext/refdata/src/refdata.rb:45:in `<module:Archiver>': Refdata: Starting debugging using REFDATA_BASE_URI http://refdatabase.refdata.ch
error in startup: invalid connection option "tty"
error in startup: /home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.8/lib/dbd/pg/database.rb:83:in `rescue in initialize'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.8/lib/dbd/pg/database.rb:40:in `initialize'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.8/lib/dbd/Pg.rb:157:in `new'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbd-pg-0.5.8/lib/dbd/Pg.rb:157:in `connect'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbi-0.5.8/lib/dbi/handles/driver.rb:33:in `connect'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/ydbi-0.5.8/lib/dbi.rb:148:in `connect'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:63:in `block in _connect'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:62:in `times'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:62:in `_connect'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:59:in `block in connect'
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:59:in `synchronize'
```

**Comment by zdavatz** [comment]
But the encoding is wrong. Need to dump the DB again.

**Comment by zdavatz** [comment]
This must be related: https://github.com/QueueClassic/queue_classic/issues/333

**Comment by zdavatz** [comment]
You have to release both: `ydbd-pg` and `ydbi`, see: https://github.com/zdavatz/ydbi#release-a-new-ydbi-gem

**Comment by zdavatz** [comment]
Ubuntu also wants a DB password:
1. sudo -u postgres psql
2. ALTER USER postgres PASSWORD 'newpassword';
