### ISSUE TITLE
Restore from Backup on Ubuntu

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#184]
1. After fixing #183
2. Running `bundle exec rackup -p 8012 --quiet`
3. Results in
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
2022-12-15 06:01:24 +0100 Starting /home/zdavatz/.rbenv/versions/3.1.0/bin/rackup
Attention: monkey-patching CSV::Cell
2022-12-15 06:01:25 +0100: /var/www/oddb.org/ext/refdata/src/refdata.rb:45:in `<module:Archiver>': Refdata: Starting debugging using REFDATA_BASE_URI http://refdatabase.refdata.ch
2022-12-15 06:01:28 +0100: /var/www/oddb.org/src/util/oddbapp.rb:1467:in `initialize': process: /home/zdavatz/.rbenv/versions/3.1.0/bin/rackup server_uri druby://127.0.0.1:10000  auxiliary  after 8.2379e-05 seconds
2022-12-15 06:01:28 +0100: /var/www/oddb.org/src/util/oddbapp.rb:1493:in `rescue in initialize': Error initializing FEHLER:  Relation »object« existiert nicht
LINE 1: SELECT content FROM object WHERE name = $1
                            ^
 with @@primary_server
```

**Comment by zdavatz** [comment]
This seems to work:
1.  `sudo su`
2. `su - postgres`
3. `dropdb ch_oddb`
4. `createdb ch_oddb`
5. check DB
6. `psql`
7.  `\l`
8.  As normal User do 
9. `bzcat 22:00-postgresql_database-ch_oddb-backup.bz2 | sudo -u postgres psql -p 5433 ch_oddb`

**Comment by zdavatz** [comment]
Set postgres Library path for ngiger: https://www.postgresql.org/docs/current/install-post.html
