### ISSUE TITLE
Debug Daemontools

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#185]
1. `ps -Af | grep readproctitle`
2. Shows the following output
```
root      109497  109494  0 Dez13 ?        00:00:00 readproctitle service errors: ...: fatal: unable to start oddb/run: access denied supervise: fatal: unable to start oddb/run: access denied supervise: fatal: unable to start oddb/run: access denied supervise: fatal: unable to start oddb/run: access denied supervise: fatal: unable to start oddb/run: access denied supervise: fatal: unable to start oddb/run: access denied supervise: fatal: unable to start oddb/run: access denied
```
3. `chmod +x svc/oddb/run`
4. Also check running ports
5. `sudo netstat -ltnp`

**Comment by zdavatz** [comment]
1. `ps -Af | grep readproctitle`
2. reports
3. `fatal: unable to run bundle: file does not exist setuidgid:`

**Comment by zdavatz** [comment]
Ok, after rebooting the VM I now get more ouput:
```
@40000000639c879f22c8af9c 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
@40000000639c879f22c8b76c 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
@40000000639c879f22c8bb54 	from /usr/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
@40000000639c879f22c924cc 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
@40000000639c879f22c92c9c 	from /usr/lib/ruby/3.0.0/bundler/cli.rb:24:in `start'
@40000000639c879f22c9346c 	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:49:in `block in <top (required)>'
@40000000639c879f22c93c3c 	from /usr/lib/ruby/3.0.0/bundler/friendly_errors.rb:128:in `with_friendly_errors'
@40000000639c879f22c9440c 	from /usr/lib/ruby/gems/3.0.0/gems/bundler-2.2.22/libexec/bundle:37:in `<top (required)>'
@40000000639c879f22c96b1c 	from /home/zdavatz/.rbenv/versions/3.1.1/bin/bundle:25:in `load'
@40000000639c879f22c972ec 	from /home/zdavatz/.rbenv/versions/3.1.1/bin/bundle:25:in `<main>'
@40000000639c87a02176a48c bundler: failed to load command: /home/zdavatz/.rbenv/versions/3.1.1/bin/rackup (/home/zdavatz/.rbenv/versions/3.1.1/bin/rackup)
@40000000639c87a02177fc4c /usr/lib/ruby/3.0.0/bundler/source/git.rb:206:in `rescue in load_spec_files': https://github.com/zdavatz/ruby-dbi is not yet checked out. Run `bundle install` first. (Bundler::GitError)
@40000000639c87a021780804 	from /usr/lib/ruby/3.0.0/bundler/source/git.rb:202:in `load_spec_files'
@40000000639c87a021780bec 	from /usr/lib/ruby/3.0.0/bundler/source/path.rb:107:in `local_specs'
@40000000639c87a021780fd4 	from /usr/lib/ruby/3.0.0/bundler/source/git.rb:170:in `specs'
@40000000639c87a0217813bc 	from /usr/lib/ruby/3.0.0/bundler/lazy_specification.rb:72:in `__materialize__'
@40000000639c87a021783acc 	from /usr/lib/ruby/3.0.0/bundler/spec_set.rb:88:in `block in materialize'
@40000000639c87a021788cd4 	from /usr/lib/ruby/3.0.0/bundler/spec_set.rb:86:in `map!'
@40000000639c87a0217890bc 	from /usr/lib/ruby/3.0.0/bundler/spec_set.rb:86:in `materialize'
@40000000639c87a0217894a4 	from /usr/lib/ruby/3.0.0/bundler/definition.rb:190:in `specs'
@40000000639c87a02178988c 	from /usr/lib/ruby/3.0.0/bundler/definition.rb:259:in `specs_for'
@40000000639c87a021789c74 	from /usr/lib/ruby/3.0.0/bundler/definition.rb:241:in `requested_specs'
@40000000639c87a02178a05c 	from /usr/lib/ruby/3.0.0/bundler/runtime.rb:91:in `block in definition_method'
@40000000639c87a02178bbb4 	from /usr/lib/ruby/3.0.0/bundler/runtime.rb:20:in `setup'
@40000000639c87a02178bf9c 	from /usr/lib/ruby/3.0.0/bundler.rb:149:in `setup'
@40000000639c87a02178c384 	from /usr/lib/ruby/3.0.0/bundler/setup.rb:20:in `block in <top (required)>'
@40000000639c87a02178c76c 	from /usr/lib/ruby/3.0.0/bundler/ui/shell.rb:136:in `with_level'
@40000000639c87a02178cb54 	from /usr/lib/ruby/3.0.0/bundler/ui/shell.rb:88:in `silence'
@40000000639c87a02178e6ac 	from /usr/lib/ruby/3.0.0/bundler/setup.rb:20:in `<top (required)>'
@40000000639c87a02178ee7c 	from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:61:in `require_relative'
@40000000639c87a02178f264 	from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:61:in `kernel_load'
@40000000639c87a02178f64c 	from /usr/lib/ruby/3.0.0/bundler/cli/exec.rb:28:in `run'
@40000000639c87a02178f64c 	from /usr/lib/ruby/3.0.0/bundler/cli.rb:474:in `exec'
@40000000639c87a021799e44 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
@40000000639c87a02179a22c 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
@40000000639c87a02179a614 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
@40000000639c87a02179a9fc 	from /usr/lib/ruby/3.0.0/bundler/cli.rb:30:in `dispatch'
@40000000639c87a02179ade4 	from /usr/lib/ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
```

**Comment by zdavatz** [comment]
`ruby -e 'puts $:'`
Outputs:
```
/home/zdavatz/.rbenv/rbenv.d/exec/gem-rehash
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/site_ruby/3.1.0/x86_64-linux
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/site_ruby
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/vendor_ruby/3.1.0
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/vendor_ruby/3.1.0/x86_64-linux
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/vendor_ruby
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/3.1.0
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/3.1.0/x86_64-linux
```

**Comment by zdavatz** [comment]
New clean install:
Install rbenv and ruby-build
git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
Add to ~/.bash_profile
echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bash_profile
echo 'eval "$(rbenv init -)"' >> ~/.bash_profile

**Comment by zdavatz** [comment]
1. the script in 
2. `svc/oddb/run`
3. is
```
#!/bin/sh
exec 2>&1
cd /var/www/oddb.org
PATH=/home/zdavatz/.rbenv/versions/3.1.1/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
exec setuidgid zdavatz bundle exec rackup -p 8012 --quiet config.ru
```
