### ISSUE TITLE
`@odba_prefetch=nil` ... `odba_instance.send`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#186]
running `jobs/import_daily` can result in:
```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `size' for #<ODDB::PatinfoDocument:0x00007f78eded74d0 @iksnrs=#<ODBA::Stub:9492040#42501786 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @name=#<ODBA::Stub:9492060#42501787 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @company=#<ODBA::Stub:9492080#42501788 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @galenic_form=nil, @effects=#<ODBA::Stub:9492100#42501789 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @amendments=nil, @contra_indications=#<ODBA::Stub:9492120#42501790 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @precautions=nil, @pregnancy=#<ODBA::Stub:9492140#42501791 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @usage=#<ODBA::Stub:9492160#42501792 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @unwanted_effects=#<ODBA::Stub:9492180#42501793 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @general_advice=#<ODBA::Stub:9492200#42501794 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @composition=nil, @packages=#<ODBA::Stub:9492220#42501795 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @distribution=nil, @fabrication=nil, @date=#<ODBA::Stub:9492240#42501796 @odba_class=ODDB::Text::Chapter @odba_container=9492020#42330856>, @odba_id=42330856, @odba_persistent=true, @odba_observers=[], @revision=2019-06-22 07:51:54.132653143 +0200, @oid=42330856, @odba_prefetch=nil>

               odba_instance.send(meth_symbol, *args, &block)
                            ^^^^^
Backtrace:
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/plugin/text_info.rb:292:in `store_patinfo_change_diff'
/var/www/oddb.org/src/plugin/text_info.rb:322:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:352:in `store_patinfo_for_all_packages'
/var/www/oddb.org/src/plugin/text_info.rb:385:in `block in update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:384:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:384:in `update_patinfo_lang'
/var/www/oddb.org/src/plugin/text_info.rb:1305:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1499:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1498:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1498:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:541:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:497:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:535:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:329:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:210:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
Similar Error on 16.12.2022

<img width="801" alt="Bildschirm­foto 2022-12-19 um 10 09 05" src="https://user-images.githubusercontent.com/4953/208329764-e35c5ee5-cf12-480b-8231-3c411b3082d5.png">

**Comment by zdavatz** [comment]
Same error on 17.12.2022

<img width="821" alt="Bildschirm­foto 2022-12-19 um 10 10 06" src="https://user-images.githubusercontent.com/4953/208329837-35b2da80-f2ee-47f9-b161-db30525b0614.png">

**Comment by zdavatz** [comment]
Restoring from the DB of 18.12. worked! Seems that sometimes ODBA IDs can confuse each other ;)
