### ISSUE TITLE
`jobs/import_swissmedic` fails 10.1.2023

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#199]
`jobs/import_swissmedic` fails:
```
Plugin: ODDB::SwissmedicPlugin

Error: NoMethodError
Message: undefined method `item=' for #<ODDB::ActiveAgent:0x00007f0739a67c40 @sequence=nil, @pointer=#<ODDB::Persistence::Pointer:0x00007f0739a67b78 @directions=[["registration", "52573"], [:sequence, "01"], [:package, "017"], [:feedback, nil]]>, @odba_persistent=true, @substance_name="Lisinoprilum", @odba_id=678315, @dose=Quanty(5,'mg'), @odba_observers=[], @substance=#<ODBA::Stub:29358280#5298 @odba_class=ODDB::Substance @odba_container=29358240#678315>, @odba_prefetch=nil, @odba_target_ids=nil, @chemical_substance=#<ODBA::Stub:29358300#4516 @odba_class=ODDB::Substance @odba_container=29358240#678315>>

                                odba_instance.send(meth_symbol, *args, &block)
                                             ^^^^^
Backtrace:
/home/zdavatz/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/oddb.org/src/model/package.rb:673:in `block in checkout'
/var/www/oddb.org/src/model/package.rb:673:in `each'
/var/www/oddb.org/src/model/package.rb:673:in `checkout'
/var/www/oddb.org/src/util/persistence.rb:258:in `issue_delete'
/var/www/oddb.org/src/util/oddbapp.rb:126:in `block in delete'
/var/www/oddb.org/src/util/failsafe.rb:10:in `failsafe'
/var/www/oddb.org/src/util/oddbapp.rb:122:in `delete'
/var/www/oddb.org/src/command/delete.rb:11:in `execute'
/var/www/oddb.org/src/util/oddbapp.rb:689:in `execute_command'
/var/www/oddb.org/src/util/oddbapp.rb:1544:in `delete'
/var/www/oddb.org/src/plugin/swissmedic.rb:519:in `block in delete'
/var/www/oddb.org/src/plugin/swissmedic.rb:502:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:502:in `each_with_index'
```

**Comment by zdavatz** [comment]
I am requesting a clarification from Swissmedic:
```
Bei der Registration 52573 auf der Zeile 4152 steht in der Spalte die Packungsgrösse "1 - 15".

https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/zugelassene_packungen_human.xlsx.download.xlsx/zugelassene_packungen_ham.xlsx

Was soll das genau bedeuten? Ist jede Packung anders gross? Sollte das nicht "1x15" heissen? Gemäss den Angaben handelt es sich bei der galenischen Form um Kapseln.
```

**Comment by zdavatz** [comment]
Ok, after the second try, this went through!
