### ISSUE TITLE
`jobs/update_rss_feeds` does not seem to update the Fachinfo RSS feed.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#207]
1. I done `bundle exec ruby jobs/update_rss_feeds`
2. It does not seem to update the Fachinfo RSS Feed: https://ch.oddb.org/de/gcc/rss/channel/fachinfo.rss
3. Last update was in 2020
4. ![0A4A4572-26AB-4580-B6F8-8C5589C9CD4B](https://user-images.githubusercontent.com/4953/213661892-c24086f1-6106-44ae-a514-f3e7247e1672.jpeg)
5. It would be great to have a job `jobs/update_fachinfo_rss`
6. This job should be a follower of `jobs/import_daily`
7. As I understand `jobs/update_rss_feeds` is already a follower of `jobs/import_daily` but it somehow does not work, it seems.

**Comment by zdavatz** [comment]
The log kind of looks good:
```
2023-01-23 08:35:31 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:108:in `block in to_html': Finished and collected garbage RSS.to_html for 6285 FIs. Using 18400 MB
2023-01-23 08:35:33 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:91:in `block in to_html': Starting RSS.to_html  fr for 6285 FI. Using 17275 MBs
2023-01-23 08:35:38 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:103:in `block in to_html': Sleeping 6 seconds in item_to_html to give cleanup some time 6285 FIs @year 2023. Using 17275 MB
2023-01-23 08:35:44 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:106:in `block in to_html': Finished RSS.to_html for 6285 FIs. Using 17275 MB
2023-01-23 08:35:47 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:108:in `block in to_html': Finished and collected garbage RSS.to_html for 6285 FIs. Using 17275 MB
2023-01-23 08:35:48 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:91:in `block in to_html': Starting RSS.to_html  en for 6285 FI. Using 17275 MBs
2023-01-23 08:35:50 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:103:in `block in to_html': Sleeping 6 seconds in item_to_html to give cleanup some time 6285 FIs @year 2023. Using 17275 MB
2023-01-23 08:35:56 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:106:in `block in to_html': Finished RSS.to_html for 6285 FIs. Using 17275 MB
2023-01-23 08:35:59 +0100: /var/www/oddb.org/src/view/rss/fachinfo.rb:108:in `block in to_html': Finished and collected garbage RSS.to_html for 6285 FIs. Using 17275 MB
2023-01-23 07:36:00 UTC update_rss_feeds : month  today 2023-01-23 with 6285 entries
```

**Comment by zdavatz** [comment]
Ok, the file is actually there, but it seems that the RSS Readers can not process the file, as it is to big ;) 138 MB.

**Comment by zdavatz** [comment]
The `newsboat` RSS reader works fine ;)
![latest-screenshot](https://user-images.githubusercontent.com/4953/214034909-87b2cef2-20b5-442e-aba1-319d037cdb44.png)
