### ISSUE TITLE
Import_daily throws an error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#209]
1. import_drugshortages resulted in
```
Plugin: ODDB::ShortagePlugin

Error: NoMethodError
Message: undefined method `values' for #<ODDB::PatinfoDocument:0x00007f6534ad1538 @revision=2023-02-13 06:22:08.867614432 +0100, @odba_observers=[], @galenic_form=nil, @effects=#<ODBA::Stub:3800480#51913221 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @odba_id=51912137, @amendments=#<ODBA::Stub:3800500#51913222 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @contra_indications=#<ODBA::Stub:3800520#51913223 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @precautions=#<ODBA::Stub:3800540#51913224 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @pregnancy=#<ODBA::Stub:3800560#51913225 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @unwanted_effects=#<ODBA::Stub:3800580#51913226 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @general_advice=#<ODBA::Stub:3800600#51913227 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @composition=#<ODBA::Stub:3800620#51913228 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @packages=#<ODBA::Stub:3800640#51913229 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @distribution=nil, @odba_persistent=true, @oid=51912137, @name=#<ODBA::Stub:3800660#51913230 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @iksnrs=#<ODBA::Stub:3800680#51913231 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @fabrication=nil, @date=#<ODBA::Stub:3800700#51913232 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @company=#<ODBA::Stub:3800720#51913233 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @usage=#<ODBA::Stub:3800740#51913234 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @odba_prefetch=nil>
Backtrace:
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/[oddb.org/src/model/sequence.rb:67:in](http://oddb.org/src/model/sequence.rb:67:in) `active_packages'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/[oddb.org/src/model/registration.rb:74:in](http://oddb.org/src/model/registration.rb:74:in) `block in active_packages'
/var/www/[oddb.org/src/model/registration.rb:73:in](http://oddb.org/src/model/registration.rb:73:in) `each'
/var/www/[oddb.org/src/model/registration.rb:73:in](http://oddb.org/src/model/registration.rb:73:in) `inject'
/var/www/[oddb.org/src/model/registration.rb:73:in](http://oddb.org/src/model/registration.rb:73:in) `active_packages'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/[oddb.org/src/util/oddbapp.rb:195:in](http://oddb.org/src/util/oddbapp.rb:195:in) `block in active_packages'
```
2. Now import_daily results in
```
Plugin: ODDB::TextInfoPlugin

Error: NoMethodError
Message: undefined method `values' for #<ODDB::PatinfoDocument:0x00007fbc06aaf090 @revision=2023-02-13 06:22:08.867614432 +0100, @odba_observers=[], @galenic_form=nil, @effects=#<ODBA::Stub:3800480#51913221 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @odba_id=51912137, @amendments=#<ODBA::Stub:3800500#51913222 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @contra_indications=#<ODBA::Stub:3800520#51913223 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @precautions=#<ODBA::Stub:3800540#51913224 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @pregnancy=#<ODBA::Stub:3800560#51913225 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @unwanted_effects=#<ODBA::Stub:3800580#51913226 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @general_advice=#<ODBA::Stub:3800600#51913227 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @composition=#<ODBA::Stub:3800620#51913228 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @packages=#<ODBA::Stub:3800640#51913229 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @distribution=nil, @odba_persistent=true, @oid=51912137, @name=#<ODBA::Stub:3800660#51913230 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @iksnrs=#<ODBA::Stub:3800680#51913231 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @fabrication=nil, @date=#<ODBA::Stub:3800700#51913232 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @company=#<ODBA::Stub:3800720#51913233 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @usage=#<ODBA::Stub:3800740#51913234 @odba_class=ODDB::Text::Chapter @odba_container=3800460#51912137>, @odba_prefetch=nil>
Backtrace:
/var/www/[oddb.org/src/model/registration.rb:241:in](http://oddb.org/src/model/registration.rb:241:in) `block in packages'
/var/www/[oddb.org/src/model/registration.rb:240:in](http://oddb.org/src/model/registration.rb:240:in) `each'
/var/www/[oddb.org/src/model/registration.rb:240:in](http://oddb.org/src/model/registration.rb:240:in) `inject'
/var/www/[oddb.org/src/model/registration.rb:240:in](http://oddb.org/src/model/registration.rb:240:in) `packages'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/var/www/[oddb.org/src/plugin/text_info.rb:1352:in](http://oddb.org/src/plugin/text_info.rb:1352:in) `block (2 levels) in report_problematic_names'
/var/www/[oddb.org/src/plugin/text_info.rb:1350:in](http://oddb.org/src/plugin/text_info.rb:1350:in) `each'
/var/www/[oddb.org/src/plugin/text_info.rb:1350:in](http://oddb.org/src/plugin/text_info.rb:1350:in) `block in report_problematic_names'
/var/www/[oddb.org/src/plugin/text_info.rb:1348:in](http://oddb.org/src/plugin/text_info.rb:1348:in) `open'
```
3. DB Backup is here: http://sl_errors.oddb.org/db/

**Comment by zdavatz** [comment]
Latest Drugshortage from oddb: https://transfer.sh/0ofGUt/drugshortage-latest.html.txt

**Comment by zdavatz** [comment]
Postgres restart did not help.

**Comment by zdavatz** [comment]
Warum wird in der Error Nachricht, die betroffene Registration nicht angezeigt?

**Comment by zdavatz** [comment]
Das Debug Log vom Feburar: https://transfer.sh/oISQSC/02.log

**Comment by ngiger** [comment]
Trying to find the concerned object. bin/admin on oddb-ci2 gives
```
ch.oddb> patinfos.values.find{ |x| x.odba_id == 51912137}.class
-> NilClass
```
But it was search in src/model/sequence.rb:6 via @packages.values, therefore I think the odba_id belong to a package and I search in bin/admin via
```
ch.oddb> packages.find{ |x| x.odba_id == 51912137}.class
-> NilClass
```
@zdavatz: Can you check whether you get also a nil value for these two queries. I suspect that the second one will give you a patinfo

**Comment by zdavatz** [comment]
<img width="787" alt="Bildschirm­foto 2023-02-15 um 09 50 59" src="https://user-images.githubusercontent.com/4953/218979165-4064405c-b868-43b3-b9be-e88e5c9b8e40.png">

**Comment by zdavatz** [comment]
```
ch.oddb> packages.find{ |x| x.odba_id == 51912137}.class
-> undefined method `values' for #<ODDB::PatinfoDocument:0x00007fba690c1900 @revision=2023-02-13 06:22:08.867614432 +0100, @odba_observers=[], @galenic_form=nil, @effects=#<ODBA::Stub:5774500#51913221 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @odba_id=51912137, @amendments=#<ODBA::Stub:5774520#51913222 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @contra_indications=#<ODBA::Stub:5774540#51913223 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @precautions=#<ODBA::Stub:5774560#51913224 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @pregnancy=#<ODBA::Stub:5774580#51913225 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @unwanted_effects=#<ODBA::Stub:5774600#51913226 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @general_advice=#<ODBA::Stub:5774620#51913227 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @composition=#<ODBA::Stub:5774640#51913228 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @packages=#<ODBA::Stub:5774660#51913229 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @distribution=nil, @odba_persistent=true, @oid=51912137, @name=#<ODBA::Stub:5774680#51913230 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @iksnrs=#<ODBA::Stub:5774700#51913231 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @fabrication=nil, @date=#<ODBA::Stub:5774720#51913232 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @company=#<ODBA::Stub:5774740#51913233 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @usage=#<ODBA::Stub:5774760#51913234 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @odba_prefetch=nil>
ch.oddb>
```

**Comment by zdavatz** [comment]
```
ch.oddb> packages.find{ |x| x.odba_id == 51912137}.class
-> undefined method `values' for #<ODDB::PatinfoDocument:0x00007fba690c1900 @revision=2023-02-13 06:22:08.867614432 +0100, @odba_observers=[], @galenic_form=nil, @effects=#<ODBA::Stub:5774500#51913221 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @odba_id=51912137, @amendments=#<ODBA::Stub:5774520#51913222 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @contra_indications=#<ODBA::Stub:5774540#51913223 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @precautions=#<ODBA::Stub:5774560#51913224 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @pregnancy=#<ODBA::Stub:5774580#51913225 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @unwanted_effects=#<ODBA::Stub:5774600#51913226 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @general_advice=#<ODBA::Stub:5774620#51913227 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @composition=#<ODBA::Stub:5774640#51913228 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @packages=#<ODBA::Stub:5774660#51913229 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @distribution=nil, @odba_persistent=true, @oid=51912137, @name=#<ODBA::Stub:5774680#51913230 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @iksnrs=#<ODBA::Stub:5774700#51913231 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @fabrication=nil, @date=#<ODBA::Stub:5774720#51913232 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @company=#<ODBA::Stub:5774740#51913233 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @usage=#<ODBA::Stub:5774760#51913234 @odba_class=ODDB::Text::Chapter @odba_container=5774460#51912137>, @odba_prefetch=nil>
ch.oddb>
```

**Comment by zdavatz** [comment]
currently testing
```
Muss jetzt leider gehen. Habe im import_daily folgenden bin/admin am laufen

$nrIds = 0; $visited=[]; registrations.values.each{|r| r.sequences.values.each{|x| $nrIds +=1; $visited << x.patinfo&.odba_id if x.patinfo&.odba_id ; x.patinfo&.odba_id }}
```

**Comment by zdavatz** [comment]
interesting output...
```
ch.oddb> $nrIds = 0; $visited=[]; registrations.values.each{|r| r.sequences.values.each{|x| $nrIds +=1; $visited << x.patinfo&.odba_id if x.patinfo&.odba_id ; x.patinfo&.odba_id }}
-> ^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[BArray
```

**Comment by ngiger** [comment]
The output is not very interesting, as it reflects some noise in the ssh channel. I refined the statement (which took about 2 minutes on oddb-ci2.
```
Time.now
$last = 0; $ids= []; $visited=[]; registrations.values.each{|r| r.packages.each{|x| next unless x&.patinfo&.odba_id; $last = r.iksnr; $ids << r.iksnr; $visited << "#{r.iksnr}:#{x.iksnr}: #{x&.patinfo&.odba_id}" }}
Time.now
```

**Comment by ngiger** [comment]
Had to adjust again:
```
> 2023-02-16 09:31:28 +0100
ch.oddb> $visited=[]; $last = 0;$idx=0;registrations.values.each_with_index{|r, index|  $last = r.iksnr; $idx=index; r.packages.each{|x| next unless x&.patinfo&.odba_id; $visited << "#{x.iksnr}: #{x&.patinfo&.odba_id}" }}
-> undefined method `values' for #<ODDB::PatinfoDocument:0x00007f44cc963e90 @odba_observers=[], @usage=#<ODBA::Stub:6199320#51913234 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @odba_id=51912137, @oid=51912137, @galenic_form=nil, @effects=#<ODBA::Stub:6199340#51913221 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @revision=2023-02-13 06:22:08.867614432 +0100, @amendments=#<ODBA::Stub:6199360#51913222 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @contra_indications=#<ODBA::Stub:6199380#51913223 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @precautions=#<ODBA::Stub:6199400#51913224 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @pregnancy=#<ODBA::Stub:6199420#51913225 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @odba_persistent=true, @unwanted_effects=#<ODBA::Stub:6199440#51913226 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @general_advice=#<ODBA::Stub:6199460#51913227 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @odba_prefetch=nil, @composition=#<ODBA::Stub:6199480#51913228 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @packages=#<ODBA::Stub:6199500#51913229 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @distribution=nil, @company=#<ODBA::Stub:6199520#51913233 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @fabrication=nil, @name=#<ODBA::Stub:6199540#51913230 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @iksnrs=#<ODBA::Stub:6199560#51913231 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @date=#<ODBA::Stub:6199580#51913232 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>>
ch.oddb> Time.now
-> 2023-02-16 09:37:21 +0100
ch.oddb> $last
-> 68792
ch.oddb> $idx
-> 13355
ch.oddb> $registrations.size
-> undefined method `size' for nil:NilClass
ch.oddb> registrations.size
-> 13356
ch.oddb> $visited.last
-> 68372: 51802125
```
Now I get to the problematic registration 68372 and get a clear error
```
 ch.oddb> registration('68792').packages
-> undefined method `values' for #<ODDB::PatinfoDocument:0x00007f44cc963e90 @odba_observers=[], @usage=#<ODBA::Stub:6199320#51913234 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @odba_id=51912137, @oid=51912137, @galenic_form=nil, @effects=#<ODBA::Stub:6199340#51913221 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @revision=2023-02-13 06:22:08.867614432 +0100, @amendments=#<ODBA::Stub:6199360#51913222 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @contra_indications=#<ODBA::Stub:6199380#51913223 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @precautions=#<ODBA::Stub:6199400#51913224 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @pregnancy=#<ODBA::Stub:6199420#51913225 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @odba_persistent=true, @unwanted_effects=#<ODBA::Stub:6199440#51913226 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @general_advice=#<ODBA::Stub:6199460#51913227 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @odba_prefetch=nil, @composition=#<ODBA::Stub:6199480#51913228 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @packages=#<ODBA::Stub:6199500#51913229 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @distribution=nil, @company=#<ODBA::Stub:6199520#51913233 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @fabrication=nil, @name=#<ODBA::Stub:6199540#51913230 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @iksnrs=#<ODBA::Stub:6199560#51913231 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>, @date=#<ODBA::Stub:6199580#51913232 @odba_class=ODDB::Text::Chapter @odba_container=6199300#51912137>>
```

**Comment by ngiger** [comment]
Now we see the error even clearer when giving
```
ch.oddb> registration('68792').sequence('00').class
-> ODDB::Sequence
ch.oddb> registration('68792').sequence('00').packages
-> ODDB::PatinfoDocument
```
Whereas I get on oddb-ci2 the following
```
ch.oddb>  registration('68792').sequence('00').packages
-> {"000"=>#<ODBA::Stub:8224420#51604356 @odba_class=ODDB::Package @odba_container=8178100#51604362>}
```
Repairing
```
registration('68792').delete_sequence('00')
registration('68792').odba_store
``
Now the registration/sequence will be recreated when running import_daily again as we have
```
ch.oddb> registration('68792').sequences
-> {}
```

**Comment by zdavatz** [comment]
Interessanterweise, ist die Packung nicht mehr zugelassen und hat auch keine Packungen mehr.
<img width="1075" alt="Bildschirm­foto 2023-02-16 um 10 10 39" src="https://user-images.githubusercontent.com/4953/219319871-1f588df8-11f9-41d1-ac71-dfa0165ca7be.png">
