### ISSUE TITLE
`import_swissmedic` error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#213]
1. running `jobs import/swissmedic` results in
2.
```
Plugin: ODDB::SwissmedicPlugin

Error: ODBA::OdbaError
Message: ODBA::OdbaError
Backtrace:
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `!'
/var/www/oddb.org/src/plugin/swissmedic.rb:1177:in `update_package'
/var/www/oddb.org/src/plugin/swissmedic.rb:1324:in `update_all_sequence_info'
/var/www/oddb.org/src/plugin/swissmedic.rb:1345:in `block in update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:1332:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:1332:in `each_with_index'
/var/www/oddb.org/src/plugin/swissmedic.rb:1332:in `update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:371:in `update'
/var/www/oddb.org/src/util/updater.rb:391:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:497:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:389:in `update_swissmedic'
jobs/import_swissmedic:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```

**Comment by zdavatz** [comment]
https://transfer.sh/4ykgqW/22:00-postgresql_database-ch_oddb-backup.bz2
