### ISSUE TITLE
Drugshortage Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#221]
``` 
Plugin: ODDB::ShortagePlugin

Error: RuntimeError
Message: Unable to parse 7680501410558 in https://www.drugshortage.ch/UebersichtaktuelleLieferengpaesse2.aspx. Found only 11 tds
Backtrace:
/var/www/oddb.org/src/plugin/shortage.rb:188:in `block in update_drugshortage'
/var/www/oddb.org/src/plugin/shortage.rb:185:in `each'
/var/www/oddb.org/src/plugin/shortage.rb:185:in `update_drugshortage'
/var/www/oddb.org/src/plugin/shortage.rb:53:in `update'
/var/www/oddb.org/src/util/updater.rb:329:in `block in update_drugshortage'
/var/www/oddb.org/src/util/updater.rb:487:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:327:in `update_drugshortage'
/var/www/oddb.org/src/util/updater.rb:203:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
Funktioniert! Die Tests laufen noch nicht.
