### ISSUE TITLE
ENAMETOOLONG, Parser mistakes Dummy Text for Product Name.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#236]
1. import_daily wirft diesen Error:
2. 
```
Plugin: ODDB::TextInfoPlugin

Error: Errno::ENAMETOOLONG
Message: File name too long @ dir_s_mkdir - /var/www/oddb.org/doc/resources/images/pi/de/Anthroposophisches_Arzneimittel_Lesen_Sie_diese_Packungsbeilage_sorgf_ltig__denn_sie_enth_lt_wichtige_Informationen__Dieses_Arzneimittel_haben_Sie_entweder_pers_nlich_von_Ihrem_Arzt_oder_Ihrer__rztin_verschrieben_erhalten_oder_Sie_haben_es_ohne__rztliche_Verschreibung_in_der_Apotheke_oder_Drogerie_bezogen__Wenden_Sie_das_Arzneimittel_gem_ss_Packungsbeilage_bzw__nach_Anweisung_des_Arztes__Apothekers_oder_Drogisten_bzw__der__rztin__Apothekerin_oder_Drogistin_an__um_den_gr_ssten_Nutzen_zu_haben__Bewahren_Sie_die_Packungsbeilage_auf__Sie_wollen_sie_vielleicht_sp_ter_nochmals_lesen__files
Backtrace:
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:406:in `fu_mkdir'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:384:in `block (2 levels) in mkdir_p'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:382:in `reverse_each'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:382:in `block in mkdir_p'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:374:in `each'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:374:in `mkdir_p'
/var/www/oddb.org/src/plugin/text_info.rb:917:in `extract_image'
/var/www/oddb.org/src/plugin/text_info.rb:1309:in `parse_textinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1502:in `block in import_swissmedicinfo'
/var/www/oddb.org/src/plugin/text_info.rb:1501:in `each'
/var/www/oddb.org/src/plugin/text_info.rb:1501:in `import_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:531:in `block in update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:487:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:525:in `update_notify_simple'
/var/www/oddb.org/src/util/updater.rb:319:in `update_textinfo_swissmedicinfo'
/var/www/oddb.org/src/util/updater.rb:210:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:41:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
1. Running the Job again worked: 
2. `bundle exec ruby jobs/update_textinfo_swissmedicinfo pi`

**Comment by zdavatz** [comment]
this error happened again with this command: `bundle exec ruby jobs/update_textinfo_swissmedicinfo --target=pi 43454 45199 48914 49537 66762 --reparse`

**Comment by zdavatz** [comment]
some parsing is going wrong here:

<img width="800" alt="Bildschirmfoto 2024-01-02 um 21 33 23" src="https://github.com/zdavatz/oddb.org/assets/4953/6dcddad1-7584-4fd5-a723-7cb0bb49b881">
