### ISSUE TITLE
Startup problem with Ruby 3.3

### ISSUE THREAD

**Issue by ngiger** [zdavatz/oddb.org#241]
In order to get fast a reliable environment for oddb developers I documented my use https://devenv.sh/ in
https://github.com/ngiger/oddb.org/blob/master/devenv.README.md
This allowed me to fix the few issues when moving to ruby 3.3 and testing them via unit test for the involved components like odba, sbsm, htmlgrid, ydbi, yus, migel and oddb.org.
Big drawback for this setup is that NixOS only provides builds for postgres 12 upto 16. Starting under Postgres 16 breaks at the line in `src/util/oddb_app.rb` with the content` @system = ODBA.cache.fetch_named('oddbapp', self){ OddbPrevalence.new  } `.
I have not digged further into this problem, but it could be related to the fact that table no longer are able to contain columns named OID.
But ch.oddb.org (and my test installation oddb-ci2) runs with postgres 10.
Therefore I installed ruby-3.3 on oddb-ci2 and pulled all my changes from https://github.com/ngiger/oddb.org. I am starting the service manually `sudo -u apache bundle-330 exec rackup --host 192.168.0.75 -p 8012 --quiet`. The service startup up without any apparent failure but when I visit with my browser http://192.168.0.75:8012/ I see the error message
```
Internal Server Error
wrong number of arguments (given 2, expected 1)
WEBrick/1.8.1 (Ruby/3.3.0/2023-12-25) at 192.168.0.75:8012 
```
and in the console I see 
```
[2024-01-31 17:54:32] INFO  WEBrick::HTTPServer#start: pid=18888 port=8012
preferences_navigation / ODDB::State::User::Preferences
192.168.0.160 - - [31/Jan/2024:17:54:36 +0100] "GET http://192.168.0.75:8012/" 200 -
[2024-01-31 17:54:36] ERROR ArgumentError: wrong number of arguments (given 2, expected 1)
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/rack-3.0.8/lib/rack/body_proxy.rb:18:in `respond_to?'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/rack-3.0.8/lib/rack/body_proxy.rb:18:in `respond_to_missing?'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/rack-3.0.8/lib/rack/lint.rb:828:in `respond_to?'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/rack-3.0.8/lib/rack/lint.rb:828:in `respond_to?'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/rackup-2.1.0/lib/rackup/handler/webrick.rb:118:in `service'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:140:in `service'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:96:in `run'
        /var/www/oddb.org/vendor/bundle/ruby/3.3.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'

```
I have no idea, why I get into this error

**Comment by zdavatz** [comment]
https://stackoverflow.com/questions/65469682/argumenterror-wrong-number-of-arguments-given-2-expected-1-after-updating-t

**Comment by zdavatz** [comment]
it works for me: 
![latest-screenshot](https://github.com/zdavatz/oddb.org/assets/4953/8260d784-d670-4480-a013-a61c630c5db5)

**Comment by zdavatz** [comment]
Do you receive any HTTP headers?

![latest-screenshot](https://github.com/zdavatz/oddb.org/assets/4953/7e15e105-d1da-467e-8488-f8362cd72fa2)
