### ISSUE TITLE
Rebuild indices fails

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#275]
1. Running: `bundle exec ruby jobs/rebuild_indices`
2. Results in
```
2024-07-10 14:02:10 +0200: /var/www/oddb.org/src/util/oddbapp.rb:1466:in `initialize': process: jobs/rebuild_indices server_uri druby://127.0.0.1:10000  auxiliary true after 8.4924e-05 seconds
2024-07-10 14:02:10 +0200: /var/www/oddb.org/src/util/oddbapp.rb:1471:in `initialize': init system starting after 0.006269542 seconds
2024-07-10 14:02:37 +0200: /var/www/oddb.org/src/model/epha_interaction.rb:67:in `read_from_csv': Took 4 seconds to load /var/www/oddb.org/data/csv/interactions_de_utf8.csv
OdbaError
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:594:in `block in update_indices'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:593:in `each'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:593:in `update_indices'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:519:in `store'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/persistable.rb:274:in `odba_isolated_store'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/persistable.rb:397:in `block in odba_store_unsaved'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/persistable.rb:394:in `each'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/persistable.rb:394:in `odba_store_unsaved'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/persistable.rb:382:in `odba_store'
ODBA::Stub was unable to replace ODBA::Index#54690825 from Hash:#1. raise OdbaError
2024-07-10 14:03:04 +0200: /var/www/oddb.org/src/util/oddbapp.rb:1492:in `rescue in initialize': Error initializing ODBA::OdbaError with @@primary_server 
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych.rb:629:in `block in load_stream': rebuild_indices atc_index
dropping: atc_index
OdbaError
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:115:in `method_missing'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:165:in `delete'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:203:in `block in drop_index'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/storage.rb:568:in `block in transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/ydbi-0.5.9/lib/dbi/handles/database.rb:209:in `transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:39:in `block in method_missing'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:29:in `next_connection'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/connection_pool.rb:38:in `method_missing'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/storage.rb:564:in `transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:564:in `transaction'
ODBA::Stub was unable to replace ODBA::Index#54690825 from Hash:#1. raise OdbaError
ODBA::OdbaError
creating: atc_index
HINWEIS:  Tabelle »atc_index« existiert nicht, wird übersprungen
undefined method `update' for #<ODDB::PatinfoDocument:0x00007f2b68695f10 @packages=#<ODBA::Stub:703420#54690583 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @distribution=nil, @revision=2024-07-10 06:51:59.984687785 +0200, @fabrication=#<ODBA::Stub:703440#54690584 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @iksnrs=#<ODBA::Stub:703460#54690585 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_observers=[], @odba_id=54688556, @name=#<ODBA::Stub:703480#54690586 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @galenic_form=nil, @effects=#<ODBA::Stub:703500#54690587 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @date=#<ODBA::Stub:703520#54690588 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @amendments=#<ODBA::Stub:703540#54690589 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @usage=#<ODBA::Stub:703560#54690590 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @contra_indications=#<ODBA::Stub:703580#54690591 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @precautions=nil, @odba_persistent=true, @pregnancy=#<ODBA::Stub:703600#54690592 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @oid=54688556, @unwanted_effects=#<ODBA::Stub:703620#54690593 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_prefetch=nil, @general_advice=#<ODBA::Stub:703640#54690594 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @company=#<ODBA::Stub:703660#54690595 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @composition=#<ODBA::Stub:703680#54690596 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>>
undefined method `update' for #<ODDB::PatinfoDocument:0x00007f2b68695f10 @packages=#<ODBA::Stub:703420#54690583 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @distribution=nil, @revision=2024-07-10 06:51:59.984687785 +0200, @fabrication=#<ODBA::Stub:703440#54690584 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @iksnrs=#<ODBA::Stub:703460#54690585 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_observers=[], @odba_id=54688556, @name=#<ODBA::Stub:703480#54690586 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @galenic_form=nil, @effects=#<ODBA::Stub:703500#54690587 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @date=#<ODBA::Stub:703520#54690588 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @amendments=#<ODBA::Stub:703540#54690589 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @usage=#<ODBA::Stub:703560#54690590 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @contra_indications=#<ODBA::Stub:703580#54690591 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @precautions=nil, @odba_persistent=true, @pregnancy=#<ODBA::Stub:703600#54690592 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @oid=54688556, @unwanted_effects=#<ODBA::Stub:703620#54690593 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_prefetch=nil, @general_advice=#<ODBA::Stub:703640#54690594 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @company=#<ODBA::Stub:703660#54690595 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @composition=#<ODBA::Stub:703680#54690596 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>>
undefined method `update' for #<ODDB::PatinfoDocument:0x00007f2b68695f10 @packages=#<ODBA::Stub:703420#54690583 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @distribution=nil, @revision=2024-07-10 06:51:59.984687785 +0200, @fabrication=#<ODBA::Stub:703440#54690584 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @iksnrs=#<ODBA::Stub:703460#54690585 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_observers=[], @odba_id=54688556, @name=#<ODBA::Stub:703480#54690586 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @galenic_form=nil, @effects=#<ODBA::Stub:703500#54690587 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @date=#<ODBA::Stub:703520#54690588 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @amendments=#<ODBA::Stub:703540#54690589 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @usage=#<ODBA::Stub:703560#54690590 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @contra_indications=#<ODBA::Stub:703580#54690591 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @precautions=nil, @odba_persistent=true, @pregnancy=#<ODBA::Stub:703600#54690592 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @oid=54688556, @unwanted_effects=#<ODBA::Stub:703620#54690593 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_prefetch=nil, @general_advice=#<ODBA::Stub:703640#54690594 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @company=#<ODBA::Stub:703660#54690595 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @composition=#<ODBA::Stub:703680#54690596 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>>
undefined method `update' for #<ODDB::PatinfoDocument:0x00007f2b68695f10 @packages=#<ODBA::Stub:703420#54690583 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @distribution=nil, @revision=2024-07-10 06:51:59.984687785 +0200, @fabrication=#<ODBA::Stub:703440#54690584 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @iksnrs=#<ODBA::Stub:703460#54690585 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_observers=[], @odba_id=54688556, @name=#<ODBA::Stub:703480#54690586 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @galenic_form=nil, @effects=#<ODBA::Stub:703500#54690587 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @date=#<ODBA::Stub:703520#54690588 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @amendments=#<ODBA::Stub:703540#54690589 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @usage=#<ODBA::Stub:703560#54690590 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @contra_indications=#<ODBA::Stub:703580#54690591 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @precautions=nil, @odba_persistent=true, @pregnancy=#<ODBA::Stub:703600#54690592 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @oid=54688556, @unwanted_effects=#<ODBA::Stub:703620#54690593 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @odba_prefetch=nil, @general_advice=#<ODBA::Stub:703640#54690594 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @company=#<ODBA::Stub:703660#54690595 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>, @composition=#<ODBA::Stub:703680#54690596 @odba_class=ODDB::Text::Chapter @odba_container=54720#54688556>>
OdbaError
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `hash'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache_entry.rb:123:in `hash'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache_entry.rb:123:in `odba_replace!'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:577:in `block in transaction_rollback'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:573:in `each'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:573:in `transaction_rollback'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:566:in `rescue in transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:565:in `transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:147:in `create_index'
/var/www/oddb.org/src/util/oddbapp.rb:1373:in `block in rebuild_indices'
ODBA::Stub was unable to replace ODBA::Index#54690825 from Hash:#1. raise OdbaError
INDEX CREATION ERROR:
ODBA::OdbaError
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `hash'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache_entry.rb:123:in `hash'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache_entry.rb:123:in `odba_replace!'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:577:in `block in transaction_rollback'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:573:in `each'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:573:in `transaction_rollback'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:566:in `rescue in transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:565:in `transaction'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/odba-1.1.8/lib/odba/cache.rb:147:in `create_index'
/var/www/oddb.org/src/util/oddbapp.rb:1373:in `block in rebuild_indices'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych.rb:629:in `block in load_stream'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych/handlers/document_stream.rb:19:in `end_document'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych/parser.rb:62:in `_native_parse'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych/parser.rb:62:in `parse'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych.rb:455:in `parse_stream'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/psych-5.1.2/lib/psych.rb:628:in `load_stream'
/var/www/oddb.org/src/util/oddbapp.rb:1354:in `rebuild_indices'
/var/www/oddb.org/src/util/oddbapp.rb:1496:in `block in method_missing'
/var/www/oddb.org/src/util/oddbapp.rb:1495:in `synchronize'
/var/www/oddb.org/src/util/oddbapp.rb:1495:in `method_missing'
jobs/rebuild_indices:15:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/rebuild_indices:12:in `<module:Util>'
jobs/rebuild_indices:11:in `<module:ODDB>'
jobs/rebuild_indices:10:in `<main>'
```

**Comment by zdavatz** [comment]
1. Abfrage von `bin/admin`
2. resultiert in
```
zdavatz@ch:/var/www/oddb.org$ bin/admin
Ignoring debug-1.7.1 because its extensions are not built. Try: gem pristine debug --version 1.7.1
Ignoring rbs-2.8.2 because its extensions are not built. Try: gem pristine rbs --version 2.8.2
ch.oddb> atc_classes.size
-> druby://127.0.0.1:10000 - #<Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 10000>
```

**Comment by zdavatz** [comment]
restored from backup helped: `https://github.com/zdavatz/oddb.org/issues/182#issuecomment-1352663624`
