### ISSUE TITLE
SSL startup fails

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#286]
1. running from commandline
2. `bundle exec rackup -p 8012 --quiet`
3. results in
```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
2024-11-21 21:00:08 +0100 Starting /home/zdavatz/.rbenv/versions/3.2.0/bin/rackup
Attention: monkey-patching CSV::Cell
error in startup: Connection reset by peer
error in startup: /home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/openssl/buffering.rb:214:in `sysread_nonblock'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/openssl/buffering.rb:214:in `read_nonblock'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/net-protocol-0.1.2/lib/net/protocol.rb:212:in `rbuf_fill'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/net-protocol-0.1.2/lib/net/protocol.rb:193:in `readuntil'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/net-protocol-0.1.2/lib/net/protocol.rb:203:in `readline'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http/response.rb:158:in `read_status_line'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http/response.rb:147:in `read_new'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http.rb:1862:in `block in transport_request'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http.rb:1853:in `catch'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http.rb:1853:in `transport_request'
/home/zdavatz/.rbenv/versions/3.2.0/lib/ruby/3.2.0/net/http.rb:1826:in `request'
```

**Comment by zdavatz** [comment]
Switching to Ruby 3.2.1 solved this issue.

**Comment by zdavatz** [comment]
1. This `openssl s_client -connect 127.0.0.1:5433`
2. results in `ungültige Länge des Startpakets` in the postgres log file.

**Comment by zdavatz** [comment]
List the ciphers: `openssl ciphers -v`
