### ISSUE TITLE
Reparse not working for `59174 63164 57209 51601`

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#294]
1. The reparse is not working for these Patinfos
2. `bundle exec ruby jobs/update_textinfo_swissmedicinfo --target=pi 59174 63164 57209 51601 -reparse`

**Comment by zdavatz** [comment]
1. ` patinfos.each{ |iksnr, pi| $stdout.puts pi.localized_name if pi.iksnrs.size == 0 };`
2. results in
-> undefined method `iksnrs' for #<ODDB::Patinfo:0x00007fc29e854248 @odba_id=28685218, @descriptions=#<ODBA::Stub:3216600#28685220 @odba_class=ODDB::SimpleLanguage::Descriptions @odba_container=3062300#28685218>, @revision=2015-05-08 07:22:09.142301293 +0200, @oid=28685218, @odba_persistent=true, @sequences=#<ODBA::Stub:3216620#28685219 @odba_class= @odba_container=3062300#28685218>, @odba_prefetch=nil, @pointer=#<ODDB::Persistence::Pointer:0x00007fc29ed72ec8 @directions=[[:patinfo, 28685218]]>, @odba_observers=[]>

**Comment by zdavatz** [comment]
1. `patinfos.values.select {|pi| !pi.sequences.select{|seq| seq.patinfo != pi }.empty? }.length`
-> 46

**Comment by zdavatz** [comment]
1. ` sequences.select {|seq| next unless seq.patinfo; !seq.patinfo.descriptions.values.select{|desc| next unless desc.iksnrs; desc.iksnrs.to_s.gsub(/[^0-9]/, '') !~ /#{seq.iksnr}/ }.empty? }.first.patinfo.description("de").iksnrs`
-> undefined method `iksnrs' for #<ODDB::Text::Chapter:0x00007fc2f98d7598 @odba_persistent=true, @sections=[#<ODDB::Text::Section:0x00007fc22bfc9438 @subheading="", @paragraphs=[#<ODDB::Text::Paragraph:0x00007fc2f98d7318 @formats=[#<ODDB::Text::Format:0x00007fc22bfc9320 @values=[], @start=0, @end=-1>], @raw_txt=nil, @text="Sie d\u00FCrfen Amvuttra nicht erhalten,", @preformatted=false, @format=#<ODDB::Text::Format:0x00007fc22bfc9320 @values=[], @start=0, @end=-1>>, #<ODDB::Text::Paragraph:0x00007fc2f98d7138 @formats=[#<ODDB::Text::Format:0x00007fc22bfc9168 @values=[], @start=0, @end=-1>], @raw_txt=nil, @text="\u00B7wenn Sie jemals eine schwere allergische Reaktion auf Vutrisiran oder einen der in Rubrik \u00ABWas ist in AMVUTTRA enthalten?\u00BB genannten sonstigen Bestandteile dieses Arzneimittels hatten.", @preformatted=false, @format=#<ODDB::Text::Format:0x00007fc22bfc9168 @values=[], @start=0, @end=-1>>, #<ODDB::Text::Paragraph:0x00007fc2f98d70e8 @formats=[#<ODDB::Text::Format:0x00007fc22bfc90f0 @values=[], @start=0, @end=-1>], @raw_txt=nil, @text="Wenn Sie sich nicht sicher sind, sprechen Sie mit Ihrem Arzt, Apotheker oder dem medizinischen Fachpersonal, bevor Sie dieses Arzneimittel erhalten.", @preformatted=false, @format=#<ODDB::Text::Format:0x00007fc22bfc90f0 @values=[], @start=0, @end=-1>>]>], @odba_id=52744963, @odba_prefetch=nil, @heading="Wann darf AMVUTTRA nicht angewendet werden?", @odba_observers=[]>

**Comment by zdavatz** [comment]
1. `sequences.select {|seq| next unless seq.patinfo; !seq.patinfo.descriptions.values.select{|desc| next unless desc.iksnrs; desc.iksnrs.to_s.gsub(/[^0-9]/, '') !~ /#{seq.iksnr}/ }.empty? }.first.iksnr`
-> undefined method `iksnrs' for #<ODDB::Text::Chapter:0x00007fc29e151310 @odba_persistent=true, @sections=[], @odba_id=53229594, @odba_prefetch=nil, @heading="TEZSPIRE\u00AE Fertigpen", @odba_observers=[]>

**Comment by ngiger** [comment]
On my laptop (where I have the database as of November 26) reparsing works. Can you update the database to download?

**Comment by zdavatz** [comment]
Full Log: https://dpaste.com/CQBW7LE6Z

**Comment by zdavatz** [comment]
1. this one `sequences.select {|seq| next unless seq.patinfo; !seq.patinfo.descriptions.values.select{|desc| next unless desc.iksnrs; desc.iksnrs.to_s.gsub(/[^0-9]/, '') !~ /#{seq.iksnr}/ }.empty? }.first.patinfo.description("de").iksnrs` 
2. results in
3. `-> undefined method `iksnrs' for nil:NilClass`

**Comment by zdavatz** [comment]
1. this one: `patinfos.each{ |iksnr, pi| $stdout.puts pi.localized_name if pi.iksnrs.size == 0 }`
2. shows
3. `-> undefined method `iksnrs' for #<ODDB::Patinfo:0x00007f6919ffb728 @odba_id=28685218, @descriptions=#<ODBA::Stub:3792140#28685220 @odba_class=ODDB::SimpleLanguage::Descriptions @odba_container=3633820#28685218>, @revision=2015-05-08 07:22:09.142301293 +0200, @oid=28685218, @odba_persistent=true, @sequences=#<ODBA::Stub:3792160#28685219 @odba_class= @odba_container=3633820#28685218>, @odba_prefetch=nil, @pointer=#<ODDB::Persistence::Pointer:0x00007f690b4944b0 @directions=[[:patinfo, 28685218]]>, @odba_observers=[]>`

**Comment by ngiger** [comment]
Please run on the server again `bundle exec ruby jobs/update_textinfo_swissmedicinfo --target=pi 59174 63164 51601 -reparse` as on oddb-ci2 this command completes without error

**Comment by zdavatz** [comment]
Getting thus
```
Parse Errors: 8
IKSNR: [51601 01 51601](tel:51601 01 51601) ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: 51601 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
/var/www/oddb.org/src/plugin/text_info.rb:285:in `store_patinfo_change_log'
/var/www/oddb.org/src/plugin/text_info.rb:323:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:371:in `block in store_patinfo_for_all_packages'
/var/www/oddb.org/src/model/sequence.rb:197:in `each'
/var/www/oddb.org/src/model/sequence.rb:197:in `each_package'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:115:in `method_missing'
IKSNR: [51601 02 51601](tel:51601 02 51601) ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: [59174 02 59174](tel:59174 02 59174) ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: 59174 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
/var/www/oddb.org/src/plugin/text_info.rb:285:in `store_patinfo_change_log'
/var/www/oddb.org/src/plugin/text_info.rb:323:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:371:in `block in store_patinfo_for_all_packages'
/var/www/oddb.org/src/model/sequence.rb:197:in `each'
/var/www/oddb.org/src/model/sequence.rb:197:in `each_package'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:115:in `method_missing'
IKSNR: [59174 03 59174](tel:59174 03 59174) ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: 59174 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
/var/www/oddb.org/src/plugin/text_info.rb:285:in `store_patinfo_change_log'
/var/www/oddb.org/src/plugin/text_info.rb:323:in `store_package_patinfo'
/var/www/oddb.org/src/plugin/text_info.rb:371:in `block in store_patinfo_for_all_packages'
/var/www/oddb.org/src/model/sequence.rb:197:in `each'
/var/www/oddb.org/src/model/sequence.rb:197:in `each_package'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:115:in `method_missing'
IKSNR: [63164 01 63164](tel:63164 01 63164) ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
```

**Comment by ngiger** [comment]
Please run the command again, to see whether it reported just a temporary problem which is corrected after showing the error shown to you.

**Comment by zdavatz** [comment]
jetzt kommt:
```
Parse Errors: 4
IKSNR: 51601 01 51601 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: 51601 01 51601 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: 59174 04 59174 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
IKSNR: 59174 02 59174 ODBA::OdbaError /home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:61:in `rescue in odba_receiver'
/home/zdavatz/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/odba-1.1.9/lib/odba/stub.rb:47:in `odba_receiver'
(eval):2:in `to_s'
```
die Links gehen nicht:
51601 gives an Error: https://ch.oddb.org./de/gcc/patinfo/reg/51601/seq/01
59174 gives an Error: https://ch.oddb.org./de/gcc/search/zone/drugs/search_query/59174/search_type/st_registration?#best_result

**Comment by zdavatz** [comment]
ch.oddb> reg = @system.registration('59174'); reg.each_sequence{ |seq| next unless seq.patinfo and seq.patinfo.pointer; delete seq.patinfo.pointer; update(seq.pointer, :patinfo => nil)}
-> Array

ch.oddb> reg = @system.registration('51601'); reg.each_sequence{ |seq| next unless seq.patinfo and seq.patinfo.pointer; delete seq.patinfo.pointer; update(seq.pointer, :patinfo => nil)}
->[#<ODBA::Stub:2708740#72855 @odba_class=ODDB::Sequence @odba_container=2146780#62515>, #<ODBA::Stub:2708760#72860 @odba_class=ODDB::Sequence @odba_container=2146780#62515>]

**Comment by ngiger** [comment]
Im ersten Fall ist der Array zu gross, um dargestellt zu werden. Meines Erachtens muss nur 51601 gelöscht werden

**Comment by zdavatz** [comment]
Der scheint nach wie vor nicht zu klappen: https://ch.oddb.org/de/gcc/patinfo/reg/51601/seq/01/pack/001

**Comment by zdavatz** [comment]
1. `ch.oddb> reg = @system.registration('51601'); reg.each_sequence{ |seq| next unless seq.patinfo and seq.patinfo.pointer; delete seq.patinfo.pointer; update(seq.pointer, :patinfo => nil)}`
2. `-> [#<ODBA::Stub:4868320#72855 @odba_class=ODDB::Sequence @odba_container=4865880#62515>, #<ODBA::Stub:4868340#72860 @odba_class=ODDB::Sequence @odba_container=4865880#62515>]`

**Comment by zdavatz** [comment]
Backup is ready: http://sl_errors.oddb.org/db/22:00-postgresql_database-ch_oddb-backup.bz2
