### ISSUE TITLE
LPPV Import gibt einen Error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#57]
```
Plugin: ODDB::LppvPlugin

Error: RuntimeError
Message: Unknown child node [xr:revisionPtr] for element [workbook]
Backtrace:
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/ooxml_object.rb:155:in `block in parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:190:in `block in each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `upto'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/nokogiri-1.8.2/lib/nokogiri/xml/node_set.rb:189:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/ooxml_object.rb:144:in `parse'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/ooxml_object.rb:427:in `block in parse_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/entry.rb:501:in `get_input_stream'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/ooxml_object.rb:427:in `parse_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/relationships.rb:90:in `block in load_related_files'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/relationships.rb:75:in `each'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/relationships.rb:75:in `load_related_files'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/relationships.rb:172:in `load_relationships'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/root.rb:68:in `block in parse_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyzip-1.2.1/lib/zip/file.rb:101:in `open'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/objects/root.rb:64:in `parse_file'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/rubyXL-3.3.1/lib/rubyXL/parser.rb:4:in `parse'
/var/www/oddb.org/src/plugin/lppv.rb:50:in `update'
/var/www/oddb.org/src/util/updater.rb:543:in `update_immediate'
/var/www/oddb.org/src/util/updater.rb:401:in `update_lppv'
/var/www/oddb.org/src/util/updater.rb:444:in `update_swissmedic_followers'
jobs/import_swissmedic:15:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```

**Comment by ngiger** [comment]
Running on oddb-ci2 test to see whether problem still exists
  

> cd /var/www/oddb
sudo -u apache bundle-250 exec ruby-250 jobs/import_swissmedic_only 

Looks like this problem was fixed. See https://github.com/weshatheleopard/rubyXL/issues/299
