### ISSUE TITLE
swissmedic import error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#61]
```
Plugin: ODDB::SwissmedicPlugin

Error: RegexpError
Message: premature end of char-class: /hynic-[d-phe\(1\)($|\s)/
Backtrace:
/var/www/oddb.org/src/plugin/parslet_compositions.rb:78:in `block (3 levels) in parse_compositions'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:78:in `each'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:78:in `find'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:78:in `block (2 levels) in parse_compositions'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:75:in `each'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:75:in `block in parse_compositions'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:71:in `select'
/var/www/oddb.org/src/plugin/parslet_compositions.rb:71:in `parse_compositions'
/var/www/oddb.org/src/plugin/swissmedic.rb:1258:in `update_all_sequence_info'
/var/www/oddb.org/src/plugin/swissmedic.rb:1284:in `block in update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:1271:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:1271:in `each_with_index'
/var/www/oddb.org/src/plugin/swissmedic.rb:1271:in `update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:330:in `update'
/var/www/oddb.org/src/util/updater.rb:422:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:527:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:420:in `update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:214:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by ngiger** [comment]
The plugin has problems parsing the new IKSNR 66540 SPECT/CT-Darstellung rezeptortragender GEP- und karzinoider Tumoren

I) Durchstechflasche 1: HYNIC-[D-Phe(1), Tyr(3)-octeotridum]trifluoroacetum 16 µg, tricinum, stanni(II) chloridum dihydricum, mannitolum, pro vitro

I will try to ignore such lines.

**Comment by zdavatz** [comment]
The Full line in space Q is `HYNIC-[D-Phe(1), Tyr(3)-octeotridum]trifluoroacetum, acidum ethylendiamini-N,N'-diaceticum`

**Comment by ngiger** [comment]
Added a unit test to oddb2xml which uses the same code: see https://github.com/ngiger/oddb2xml/commit/d18d1615e710cdb4b2a43c97e0950f77dc0d3713

**Comment by ngiger** [comment]
After parsing I see the following info 

> Packungsbestandteile
Bezeichnung 	
II
Galenische Form 	Markierungsbesteck
Excipiens 	Pro Vitro
Wirkstoffe	Stärke
Acidum Ethylendiamini-N,n'-Diaceticum	10 mg
Hilfsstoffe
Dinatrium Phosphat Dodecahydrat
Natrium Hydroxid
