### ISSUE TITLE
ODDB.org Report - Med-Drugs - Swissmedic 06/2018 - SL 08/2018

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#64]
Im File sind wieder Vet-Produkte vorhanden. Das ist komisch.

Siehe file: https://ywesee.slack.com/files/U27FC8WLA/FCB20PPRC/med-drugs-20180805.xls

**Comment by zdavatz** [comment]
warum die Neuregistrierungen nicht mehr im Update sind und uns danach ein neues File, in welchem die 29 Produkte auch enthalten sind

**Comment by zdavatz** [comment]
![cd1caa24-72f8-475a-8cec-80d8aa361746](https://user-images.githubusercontent.com/4953/44408648-10f98980-a561-11e8-8621-e72153d21df7.png)

**Comment by ngiger** [comment]
Habe den Fehler gefunden. 
bin/admin auf thinpower zeigt folgendes:
ch.oddb> registration('10175').production_science
-> Phytoarzneimittel
Dies sollte jedoch ein Tierazneimittel sein.

Wenn die Spalte Heilmittelcode  jedoch falsch ist, wird sie beim Import nie neu gesetzt noch die Registration gelöscht.

 Siehe https://github.com/zdavatz/oddb.org/blob/master/src/plugin/swissmedic.rb#L1161 und folgende

**Comment by ngiger** [comment]
Sollte mit https://github.com/ngiger/oddb.org/commit/dd2b7e493739f5299bdcaa6e2a3bf0733db30e80 gelöst sein. 
Erzeugt in log/oddb/debug/2018/08.log Einträge wie

     2018-08-30 17:13:17 +0200: /var/www/oddb.org/src/plugin/swissmedic.rb:136:in `block in store_found_packages': store_found_packages delete Tierarzneimittel 66827

**Comment by zdavatz** [comment]
Packungen und Präparateliste-latest auf thin gelöscht und Import neu gestartet im Screen 24697.

**Comment by zdavatz** [comment]
Ok, jetzt haben wir den folgenden Error:
```
Plugin: ODDB::SwissmedicPlugin

Error: NoMethodError
Message: private method `sequence' called for nil:NilClass
Backtrace:
/var/www/oddb.org/src/plugin/swissmedic.rb:482:in `block in delete'
/var/www/oddb.org/src/plugin/swissmedic.rb:469:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:469:in `each_with_index'
/var/www/oddb.org/src/plugin/swissmedic.rb:469:in `delete'
/var/www/oddb.org/src/plugin/swissmedic.rb:341:in `update'
/var/www/oddb.org/src/util/updater.rb:422:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:527:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:420:in `update_swissmedic'
jobs/import_swissmedic:14:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_swissmedic:12:in `<module:Util>'
jobs/import_swissmedic:11:in `<module:ODDB>'
jobs/import_swissmedic:10:in `<main>'
```
Siehe Screen _24697_ auf Thin.

**Comment by ngiger** [comment]
Habe ich auch gesehen. Teste einen Fix dazu lokal.

**Comment by zdavatz** [comment]
Der Fix ist hier d65d6b52e00dc392a6b513b4e654. 

Ich habe den Importer nochmals neu gestartet.

**Comment by zdavatz** [comment]
Looking good! :+1:

**Comment by zdavatz** [comment]
Ad. us. vet sind nach wie vor im med-drugs update enthalten. Sie Email vom 1.9.2018.

**Comment by zdavatz** [comment]
Ah. Alle ad. us. vet haben jetzt Code 14. Das ist wohl, weil wir sie gelöscht haben.
