### ISSUE TITLE
Drugshortage OpenURI 404 error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#75]
There seems to be an error with getting the Drugshortages:
```
Plugin: ODDB::ShortagePlugin

Error: OpenURI::HTTPError
Message: 404 Not Found
Backtrace:
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:377:in `open_http'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:735:in `open'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/open-uri.rb:35:in `open'
/var/www/oddb.org/src/util/latest.rb:21:in `fetch_with_http'
/var/www/oddb.org/src/util/latest.rb:40:in `get_latest_file'
/var/www/oddb.org/src/plugin/shortage.rb:235:in `get_latest_nomarketing_file'
/var/www/oddb.org/src/plugin/shortage.rb:230:in `update_nomarketing'
/var/www/oddb.org/src/plugin/shortage.rb:52:in `update'
/var/www/oddb.org/src/util/updater.rb:369:in `block in update_drugshortage'
```

**Comment by ngiger** [comment]
Die URL wurde der Datei wurde geändert auf:
https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/liste_der_meldungennicht-inverkehrbringenvertriebsunterbruchfuerhomant.xlsx.download.xlsx/liste_der_meldungennicht-inverkehrbringenvertriebsunterbruchfuer.xlsx

**Comment by zdavatz** [comment]
Achtung, obiger Link hat ein leeres XLSX hinterlegt. Das ist der korrekte Link: https://www.swissmedic.ch/dam/swissmedic/de/dokumente/internetlisten/meldungen_art11_ham.xlsx.download.xlsx/Liste%20Meldungen%2011%20VAM.xlsx

**Comment by ngiger** [comment]
Korrigiert. Auf thinpower gepullt. In screen update_drugshortage neu gestartet.
