### ISSUE TITLE
running "sudo -u apache /usr/local/bin/bundle-250 exec /usr/local/bin/ruby-250 jobs/update_atc_dosing_link"

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#79]
results in 
```
Took 1 seconds to load /var/www/oddb.org/data/csv/interactions_de_utf8.csv
ArgumentError: invalid byte sequence in US-ASCII when updating index 'atc_index_company' with a ODDB::AtcClass
["/var/www/oddb.org/src/model/company.rb:173:in `split'", "/var/www/oddb.org/src/model/company.rb:173:in `search_terms'", "/var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.5/lib/odba/stub.rb:112:in `method_missing'", "(eval):3:in `block in proc_resolve_search_term'"]
[...]
```

**Comment by zdavatz** [comment]
this may be related to the Export error of oddb2.csv and oddb.csv

**Comment by zdavatz** [comment]
```
Plugin: ODDB::CsvExportPlugin

Error: ArgumentError
Message: invalid byte sequence in US-ASCII
Backtrace:
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/csv.rb:2095:in `count'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/csv.rb:2095:in `block in init_separators'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/csv.rb:1698:in `map'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/csv.rb:1698:in `<<'
/usr/local/ruby-2.5.0/lib/ruby/2.5.0/csv.rb:1200:in `generate_line'
/var/www/oddb.org/src/view/drugs/csv_result.rb:487:in `block in to_csv'
/var/www/oddb.org/src/view/drugs/csv_result.rb:486:in `collect'
/var/www/oddb.org/src/view/drugs/csv_result.rb:486:in `to_csv'
/var/www/oddb.org/src/view/drugs/csv_result.rb:493:in `block in to_csv_file'
/var/www/oddb.org/src/view/drugs/csv_result.rb:492:in `open'
/var/www/oddb.org/src/view/drugs/csv_result.rb:492:in `to_csv_file'
/var/www/oddb.org/src/plugin/csv_export.rb:62:in `_export_drugs'
/var/www/oddb.org/src/plugin/csv_export.rb:32:in `export_drugs'
/var/www/oddb.org/src/util/updater.rb:105:in `block in export_oddb_csv'
/var/www/oddb.org/src/util/updater.rb:526:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:103:in `export_oddb_csv'
jobs/export_oddb_csv:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/export_oddb_csv:12:in `<module:Util>'
jobs/export_oddb_csv:11:in `<module:ODDB>'
jobs/export_oddb_csv:10:in `<main>'
```
