### ISSUE TITLE
Fix US ASCII Med-Drugs Error.

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#81]
Plugin: ODDB::OuwerkerkPlugin

Error: ArgumentError
Message: invalid byte sequence in US-ASCII
Backtrace:
/var/www/oddb.org/src/plugin/ouwerkerk.rb:184:in `gsub!'
/var/www/oddb.org/src/plugin/ouwerkerk.rb:184:in `block (2 levels) in export_xls'
/var/www/oddb.org/src/plugin/ouwerkerk.rb:182:in `each'
/var/www/oddb.org/src/plugin/ouwerkerk.rb:182:in `block in export_xls'
/var/www/oddb.org/src/plugin/ouwerkerk.rb:181:in `each'
/var/www/oddb.org/src/plugin/ouwerkerk.rb:181:in `export_xls'
/var/www/oddb.org/src/util/exporter.rb:155:in `export_swissdrug_xls'
/var/www/oddb.org/src/util/updater.rb:150:in `block in export_ouwerkerk'
/var/www/oddb.org/src/util/updater.rb:511:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:149:in `export_ouwerkerk'
/var/www/oddb.org/src/util/updater.rb:305:in `update_bsv_followers'
/var/www/oddb.org/src/util/updater.rb:219:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'

**Comment by zdavatz** [comment]
related to: https://github.com/zdavatz/oddb.org/issues/74#issuecomment-498182075
