### ISSUE TITLE
Import Swissmedic Error 5.12.2019

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#93]
`jobs/import_daily` resulted in

```
Plugin: ODDB::SwissmedicPlugin

Error: NoMethodError
Message: undefined method `push' for nil:NilClass
Did you mean?  puts
Backtrace:
/var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/stub.rb:112:in `method_missing'
/var/www/oddb.org/src/model/package.rb:273:in `create_part'
/var/www/oddb.org/src/plugin/swissmedic.rb:1151:in `update_package'
/var/www/oddb.org/src/plugin/swissmedic.rb:1291:in `update_all_sequence_info'
/var/www/oddb.org/src/plugin/swissmedic.rb:1312:in `block in update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:1299:in `each'
/var/www/oddb.org/src/plugin/swissmedic.rb:1299:in `each_with_index'
/var/www/oddb.org/src/plugin/swissmedic.rb:1299:in `update_registrations'
/var/www/oddb.org/src/plugin/swissmedic.rb:351:in `update'
/var/www/oddb.org/src/util/updater.rb:406:in `block in update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:511:in `wrap_update'
/var/www/oddb.org/src/util/updater.rb:404:in `update_swissmedic'
/var/www/oddb.org/src/util/updater.rb:212:in `run'
jobs/import_daily:13:in `block in <module:Util>'
/var/www/oddb.org/src/util/job.rb:40:in `run'
jobs/import_daily:12:in `<module:Util>'
jobs/import_daily:11:in `<module:ODDB>'
jobs/import_daily:10:in `<main>'
```

**Comment by zdavatz** [comment]
Restarted with

`jobs/import_swissmedic`

seems to work.
