### ISSUE TITLE
FATAL:  sorry, too many clients already (DBI::OperationalError)

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/oddb.org#97]
```
[DEPRECATED] By requiring 'spreadsheet/excel' you are loading a Compatibility
             layer which provides a drop-in replacement for Spreadsheet::Excel
             versions <= 0.3.5.1. This code will be removed in Spreadsheet
             version 1.0.0
/var/www/oddb.org/src/view/drugs/resultlist.rb:25: warning: already initialized constant HtmlGrid::List::BACKGROUND_SUFFIX
/var/www/oddb.org/vendor/ruby/2.5.0/gems/htmlgrid-1.1.4/lib/htmlgrid/list.rb:34: warning: previous definition of BACKGROUND_SUFFIX was here
Traceback (most recent call last):
        18: from jobs/import_daily:7:in `<main>'
        17: from jobs/import_daily:7:in `require'
        16: from /var/www/oddb.org/src/util/job.rb:6:in `<top (required)>'
        15: from /var/www/oddb.org/src/util/job.rb:6:in `require'
        14: from /var/www/oddb.org/etc/db_connection.rb:10:in `<top (required)>'
        13: from /var/www/oddb.org/etc/db_connection.rb:10:in `new'
        12: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:22:in `initialize'
        11: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `connect'
        10: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `synchronize'
         9: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:59:in `block in connect'
         8: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `_connect'
         7: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:62:in `times'
         6: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/odba-1.1.6/lib/odba/connection_pool.rb:63:in `block in _connect'
         5: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/ydbi-0.5.6/lib/dbi.rb:148:in `connect'
         4: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/ydbi-0.5.6/lib/dbi/handles/driver.rb:33:in `connect'
         3: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/ydbd-pg-0.5.6/lib/dbd/Pg.rb:157:in `connect'
         2: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/ydbd-pg-0.5.6/lib/dbd/Pg.rb:157:in `new'
         1: from /var/www/oddb.org/vendor/ruby/2.5.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:40:in `initialize'
/var/www/oddb.org/vendor/ruby/2.5.0/gems/ydbd-pg-0.5.6/lib/dbd/pg/database.rb:83:in `rescue in initialize': FATAL:  sorry, too many clients already (DBI::OperationalError)
```

**Comment by ngiger** [comment]
To fix this problem on thinpower I did the following maintenance task:

     svc -d /service/ch* /service/migel /service/ydim /service/yus
     /etc/init.d/postgresql-10.1 restart
     svc -u  /service/yus  /service/migel /service/ydim /service/ch*

After a couple of minutes I was able to see ch.oddb.org again.
Restarted import_daily in the corresponding screen.

**Comment by zdavatz** [comment]
Great thank you!

**Comment by zdavatz** [comment]
`yus` musste noch mit `svc -k /service/yus/` neu gestartet werden.

**Comment by zdavatz** [comment]
This happened again on 2.6.2021.

**Comment by zdavatz** [comment]
this happened again on 1.8.2021.

**Comment by zdavatz** [comment]
this happend again on 20.9.2021.

**Comment by zdavatz** [comment]
happended again on 1.9.2022

**Comment by zdavatz** [comment]
Diese beiden Prozesse greifen auch auf `postgresql` zu:
1. exec sudo -u apache bundle-311 exec rackup -p 8212 -e "APPNAME='crawler'" --quiet
2. exec sudo -u apache bundle-311  exec rackup -p 8112  -e "APPNAME='google_crawler'" --quiet

**Comment by zdavatz** [comment]
Ok, ich versuche jetzt das:
```
max_connections = 300
shared_buffers = 4GB
```
